(function(d){var g=window.AmazonUIPageJS||window.P,l=g._namespace||g.attributeErrors,c=l?l("DetailPageMobileIconFarmAssets@common","DetailPageMobileIconFarm"):g;c.guardFatal?c.guardFatal(d)(c,window):c.execute(function(){d(c,window)})})(function(d,g,l){d.when("A","ready").register("get-icon-farm-page-state",function(c){return{parseJSON:function(e){var b;try{b=c.$("#"+e).find('script[data-a-state\x3d"{"key":"iconfarm-state"}"]').html()}catch(a){console.log(a.message)}b?e=c.$.parseJSON(b):(c.state.parse(),
e=c.state("iconfarm-state"));return e}}});d.declare("iconfarm-metrics-constants",{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",METRIC_TYPE:{GLANCE_VIEW:"GLANCE_VIEW",ICON_CLICK:"ICON_CLICK",SECONDARY_PAGE_OPEN:"SECONDARY_PAGE_OPEN",SECONDARY_PAGE_CLOSE:"SECONDARY_PAGE_CLOSE",FULL_RETURN_POLICY:"FULL_RETURN_POLICY",PAGE_DATA_MISSING:"PAGE_DATA_MISSING",ABSENT:"ABSENT"},REF_MARKER_PREFIX:{ICON_FARM_WIDGET:"iconfarm_wid",AMAZON_DELIVERED:"iconfarm_ad",
RETURNS_POLICY:"iconfarm_rp",PAY_ON_DELIVERY:"iconfarm_pod",WARRANTY:"iconfarm_wr",EASY_CARE:"iconfarm_ec",AMAZON_PROTECT:"iconfarm_ap",NO_CONTACT_DELIVERY:"iconfarm_ncd",GENERIC_RETURN_POLICY:"iconfarm_grp",MULTIPLE_SPECIFIC_RETURN_POLICY:"iconfarm_msrp",SINGLE_SPECIFIC_RETURN_POLICY:"iconfarm_ssrp",PAYMENTS_AND_SECURITY:"iconfarm_ps",PAY_ON_DELIVERY_ACTIVE:"iconfarm_pod_active",PAY_ON_DELIVERY_INACTIVE:"iconfarm_pod_inactive",WARRANTY_EU:"iconfarm_wr_eu",AMAZON_MANAGED_DELIVERY:"iconfarm_amd",AMAZON_DELIVERED_MENA:"iconfarm_ad_mena",
SAFE_PAYMENTS:"iconfarm_sp",STATIC_RETURNS_POLICY:"iconfarm_srp",GENERIC_RETURNS_POLICY:"iconfarm_grp",SUPPORT_POLICY:"iconfarm_supp",WARRANTY360:"iconfarm_wr360"},REF_MARKER_SUFFIX:{GLANCE_VIEW:"_gv",ICON_CLICK:"_clk",SECONDARY_PAGE_OPEN:"_sp_op",SECONDARY_PAGE_CLOSE:"_sp_cl",FULL_RETURN_POLICY:"_frp",ABSENT:"_noavail"},NEXUS_CONFIG:{NEXUS_PRODUCER_ID:"a2i-dpx",NEXUS_SCHEMA_ID:"a2i.dpx.WidgetImpressions.3"},LOGGER_CONFIG:{NEXUS_LOGGER:"nexus"}});d.when("A","iconfarm-return-policy-metric-logger",
"iconfarm-pay-on-delivery-metric-logger","iconfarm-default-metric-logger").register("iconfarm-icon-metric-factory",function(c,e,b,a){return{getIconMetric:function(c){switch(c){case "RETURNS_POLICY":return e;case "PAY_ON_DELIVERY":return b;default:return a}}}});d.when("A","iconfarm-metrics-constants","get-icon-farm-page-state","iconfarm-icon-metric-factory","ready").register("iconfarm-metricLogger",function(c,e,b,a){return{log:function(f,h,m){if(f&&h&&e.REF_MARKER_PREFIX[f]&&e.REF_MARKER_SUFFIX[h]){var d=
b.parseJSON(e.ICON_FARM_PAGE_STATE_HOLDER_DIV);d&&a.getIconMetric(f).log(f,h,c.$.extend(!0,{asin:d.asin,merchantId:d.merchantId,remoteAddress:d.remoteAddress,isInternal:d.isInternal,isRobot:d.isRobot},m))}}}});d.when("A","ready").register("iconfarm-postmetric",function(){return{postCountMetric:function(c){if("undefined"!==typeof c){var e=g.ue;if(e){var b=e.count(c)||0;e.count(c,b+1)}}},postTimeMetric:function(c,e){if("undefined"!==typeof c&&"undefined"!==typeof e){var b=g.ue;b&&b.count(c,e)}}}});
d.when("A","ready").register("iconfarm-metric-cache",function(c){var e=[],b=function(a){if(!(a&&a.asin&&a.merchantId&&a.ref&&a.loggerType))return!1;var b=!1;c.each(e,function(c,e){c.asin===a.asin&&c.merchantId===a.merchantId&&c.ref===a.ref&&c.loggerType===a.loggerType&&(b=!0)});return b};return{isPresent:b,add:function(a){return a&&a.asin&&a.merchantId&&a.ref&&a.loggerType?b(a)?!1:(e.push(a),!0):!1},reset:function(){e=[]}}});"use strict";d.when("A","iconfarm-metric-cache","iconfarm-metrics-constants",
"ready").register("iconfarm-Nexus-Service",function(c,e,b){return{log:function(a){if(e.add(a)){var f={};f.producerId=b.NEXUS_CONFIG.NEXUS_PRODUCER_ID;f.schemaId=b.NEXUS_CONFIG.NEXUS_SCHEMA_ID;f.refMarker=a.ref;f.pageAsin=a.asin;f.pageType=c.capabilities?c.capabilities.mobile?c.capabilities.isAmazonApp?"DetailWebView":"DetailAW":"Detail":"";f.subPageType="IconFarm";f.server=g?g.ue_sn:"";f.merchantId=a.merchantId;f.remoteAddress=a.remoteAddress;f.isInternal=a.isInternal?1:0;f.isRobot=a.isRobot?1:0;
if(a=g.ue)try{a.event&&a.event(f,b.NEXUS_CONFIG.NEXUS_PRODUCER_ID,b.NEXUS_CONFIG.NEXUS_SCHEMA_ID)}catch(d){a.count("NexusLoggerFailure",1)}}}}});d.when("A","iconfarm-Nexus-Service","iconfarm-metrics-constants","iconfarm-postmetric","ready").register("iconfarm-default-metric-logger",function(c,e,b,a){return{log:function(f,d,m){m=JSON.parse(JSON.stringify(m));e.log(c.$.extend(!0,m,{ref:b.REF_MARKER_PREFIX[f]+b.REF_MARKER_SUFFIX[d],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));a.postCountMetric(b.REF_MARKER_PREFIX[f]+
b.REF_MARKER_SUFFIX[d])}}});d.when("A","iconfarm-Nexus-Service","iconfarm-metrics-constants","iconfarm-postmetric","get-icon-farm-page-state","ready").register("iconfarm-return-policy-metric-logger",function(c,e,b,a,d){var h=function(){var a=d.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV);if(a&&a.RETURNS_POLICY&&a.RETURNS_POLICY.secondaryViewData&&a.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies)switch(a.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies.length){case 0:return"GENERIC_RETURN_POLICY";
case 1:return"SINGLE_SPECIFIC_RETURN_POLICY";default:return"MULTIPLE_SPECIFIC_RETURN_POLICY"}};return{log:function(d,f,k){d=h()||d;k=JSON.parse(JSON.stringify(k));e.log(c.$.extend(!0,k,{ref:b.REF_MARKER_PREFIX[d]+b.REF_MARKER_SUFFIX[f],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));a.postCountMetric(b.REF_MARKER_PREFIX[d]+b.REF_MARKER_SUFFIX[f])}}});d.when("A","iconfarm-Nexus-Service","iconfarm-metrics-constants","iconfarm-postmetric","get-icon-farm-page-state","ready").register("iconfarm-pay-on-delivery-metric-logger",
function(c,d,b,a,f){return{log:function(h,g,l){var k;k=(k=f.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV))&&k.PAY_ON_DELIVERY&&k.PAY_ON_DELIVERY.isEligible?k.PAY_ON_DELIVERY.isEligible?"PAY_ON_DELIVERY_ACTIVE":"PAY_ON_DELIVERY_INACTIVE":void 0;h=k||h;l=JSON.parse(JSON.stringify(l));d.log(c.$.extend(!0,l,{ref:b.REF_MARKER_PREFIX[h]+b.REF_MARKER_SUFFIX[g],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));a.postCountMetric(b.REF_MARKER_PREFIX[h]+b.REF_MARKER_SUFFIX[g])}}})});
/* ******** */
(function(d){var g=window.AmazonUIPageJS||window.P,k=g._namespace||g.attributeErrors,a=k?k("DetailPageMobileIconFarmAssets@desktop","DetailPageMobileIconFarm"):g;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,g,k){d.when("A","a-popover","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","ready").register("icon-farm-desktop-popover",function(a,p,e,b,c){var f=function(e){var f=e.data("name");a.off("a:popover:beforeShow:"+f);a.on("a:popover:beforeShow:"+
f,function(a){b.log(f,c.METRIC_TYPE.ICON_CLICK);b.log(f,c.METRIC_TYPE.SECONDARY_PAGE_OPEN)});a.off("a:popover:beforeHide:"+f);a.on("a:popover:beforeHide:"+f,function(a){b.log(f,c.METRIC_TYPE.SECONDARY_PAGE_CLOSE)})};return{init:function(){for(var b=a.$(e.ICON_FARM_CONTAINER_CLASS),c=0;c<b.length;c++){var d=a.$(b[c]),h=d.data(e.TYPE_PARAM);if(h&&h===e.TYPE_PARAM_VALUE_CUSTOM_POP_OVER){var h=d,n=a.$("#"+h.data(e.POPOVER_CONTENT_PARAM)),n={activate:e.POPOVER_ACTIVATION,position:e.POPOVER_POSITION,width:e.POPOVER_WIDTH,
inlineContent:n.html(),name:h.data("name")};p.create(h,n);f(d)}}}}});d.when("A","get-icon-farm-page-state","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","ready").register("icon-farm-desktop-returns-policy",function(a,d,e,b,c){a.declarative("returns-policy-url","click",function(a){b.log("RETURNS_POLICY",c.METRIC_TYPE.FULL_RETURN_POLICY);a=d.parseJSON(e.ICON_FARM_PAGE_STATE_HOLDER_DIV);g.open(a.RETURNS_POLICY.genericReturnPolicyURL,"_blank")});a.off("a:popover:beforeShow:return-policy-secondary-view");
a.on("a:popover:beforeShow:return-policy-secondary-view",function(a){b.log("RETURNS_POLICY",c.METRIC_TYPE.ICON_CLICK);b.log("RETURNS_POLICY",c.METRIC_TYPE.SECONDARY_PAGE_OPEN)});a.off("a:popover:beforeHide:return-policy-secondary-view");a.on("a:popover:beforeHide:return-policy-secondary-view",function(a){b.log("RETURNS_POLICY",c.METRIC_TYPE.SECONDARY_PAGE_CLOSE)});return{init:function(){}}});d.when("A","IconFarmPageStateParserService","icon-farm-desktop-popover","icon-farm-desktop-returns-policy",
"iconfarm-metricLogger","icon-farm-constants","iconfarm-metrics-constants","iconfarm-metric-cache","atf","ready").execute(function(a,d,e,b,c,f,l,g){function m(){g.reset();a.loadImageManually(a.$(".icon-box"));e.init();b.init();h()}var h=function(){var b=a.$("#icon-farm-widget");b&&b.length?c.log("ICON_FARM_WIDGET",l.METRIC_TYPE.GLANCE_VIEW):c.log("ICON_FARM_WIDGET",l.METRIC_TYPE.ABSENT);(b=a.$(".icon-container"))&&b.length&&b.each(function(){c.log(a.$(this).data("name"),l.METRIC_TYPE.GLANCE_VIEW)})};
m();a.on("a:pageUpdate",function(){var b;a:{try{if(a.$("#"+f.ICON_FARM_V2_FEATURE_DIV).find("script").length){b=f.ICON_FARM_V2_FEATURE_DIV;break a}if(a.$("#"+f.ICON_FARM_V2_PRIMARY_FEATURE_DIV).find("script").length){b=f.ICON_FARM_V2_PRIMARY_FEATURE_DIV;break a}c.log("ICON_FARM_WIDGET",l.PAGE_DATA_MISSING)}catch(e){c.log("ICON_FARM_WIDGET",l.PAGE_DATA_MISSING)}b=void 0}b&&d.isNewState(b,f.ICON_FARM_STATE)&&(b=d.processState(b,f.ICON_FARM_STATE),a.objectIsEmpty(b)||m())})});d.declare("icon-farm-constants",
{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_V2_FEATURE_DIV:"iconfarmv2_feature_div",ICON_FARM_V2_PRIMARY_FEATURE_DIV:"iconFarmV2InsidePrimary_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",ICON_FARM_CONTAINER_CLASS:".icon-container",ICON_FARM_SECONDARY_VIEW_HOLDER_ID:"#icon-farm-secondary-view-holder",ICON_FARM_STATE:"iconfarm-state",POPOVER_ACTIVATION:"onclick",POPOVER_POSITION:"triggerBottom",POPOVER_WIDTH:"533",POPOVER_CONTENT_PARAM:"iconContent",TYPE_PARAM:"type",
TYPE_PARAM_VALUE:"bottom-sheet",TYPE_PARAM_VALUE_CUSTOM_POP_OVER:"custom-pop-over"});(function(){d.when("A","atf","ready").register("IconFarmPageStateParserService",function(a){function d(e,b){b='script[data-a-state\x3d"'+JSON.stringify({key:b})+'"]';return a.$("#"+e).find(b)}return{processState:function(e,b){var c;try{var f=d(e,b),g=f[0];c=f.html();var k=a.parseJSON(c);a.state(b,k);a.$.data(g,"state_processed",!0);return k}catch(m){console.log(m)}return a.state(b)},isNewState:function(e,b){try{return!a.$.data(d(e,
b)[0],"state_processed")}catch(c){console.warn("Unable to determine state status",c)}return!1}}})})()});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageBylineInfoAssets@core","DetailPageBylineInfo"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
