(function(g){var m=window.AmazonUIPageJS||window.P,n=m._namespace||m.attributeErrors,u=n?n("CustomerReviewsCommonAssets",""):m;u.guardFatal?u.guardFatal(g)(u,window):u.execute(function(){g(u,window)})})(function(g,m,n){function u(){}g.when("A","cr-log-utils","cr-streaming-utils").register("cr-ajax-model",function(b,d,c){function a(a){k[a]&&(k[a].abort(),delete k[a])}function e(l,f,q,r,v,t,g,n){f=f||{};f.params=f.params||{};t=t?t:p++;v=v?v:f.error||function(){};r=r?r:0;q=q?q:2;n=n?n:"FATAL";var u=
"FATAL"===n?0:1,w=f.finallyCallback||function(){};g||(g="reviewsAjax"+h++,m.uet&&m.uet("tc",g));f.params.scope=g;f.contentType=f.contentType||"application/x-www-form-urlencoded;charset\x3dUTF-8";var x=f.success||function(){};f.success=function(a){delete k[t];"function"===typeof x&&x(a);"function"===typeof w&&w(a)};f.error=function(h,b,c){h=h||{};var k=(h.http||{}).status||"[]";if(401===k){var p;p=h;var x=v,y=p.http.getResponseHeader("x-amz-re-authentication-url");y?("function"===typeof x&&x(p),"function"===
typeof w&&w(p),d.logCount("AjaxRedirectToReAuthenticationUrl",1),m.location=y,p=!0):p=!1;if(p)return;r=q}a(t);r++;r<q?(b="AJAX Post to "+l+" from "+m.location.href+" failed, status code passed through parameter was: "+b+", status code extracted from XHR HTTP object was: "+k+", attempt "+r+" of "+q+", error message was: \n "+c,d.logError(b,"WARN"),e(l,f,q,r,v,t,g,n)):(b="AJAX Post to "+l+" from "+m.location.href+" failed, status code passed through parameter was: "+b+", status code extracted from XHR HTTP object was: "+
k+", exhausted "+q+" attempt(s), error message was: \n "+c,d.logError(b,n),d.logCount("AjaxFailureFatal",u),"function"===typeof v&&v(h),"function"===typeof w&&w(h))};"function"!==typeof f.chunk&&(f.chunk=function(a){"appendFadeIn"===a[0]?c.appendFadeIn(a):"replace"===a[0]&&c.replace(a)});k[t]=b.post(l,f);return t}var h=0,p=1,k={};return{abort:a,post:e,postWithoutFatals:function(a,h,b,c,d,k,p){return e(a,h,b,c,d,k,p,"WARN")}}});"use strict";g.when("A","cr-jQuery","cr-log-utils","cr-number-utils").register("cr-A",
function(b,d,c,a){b.getListFromState=function(a){var c=b.map(d("#cr-state-object, .cr-state-object"),function(a){return d(a).data("state")});return b.reduce(c,function(b,c){c!==n&&c[a]!==n&&b.push(c[a]);return b},[])};b.getValueFromState=function(a){var e=b.getListFromState(a);1<e.length&&c.logError("More than one  value defined for key: "+a,"ERROR");return e[0]};var e={top:-100,left:-100};b.inView=function(a){a=a||d();if("function"===typeof a.offset){var b=(a.offset()||e).top-d(m).scrollTop();a=
0<=b;b=b<d(m).height();return a&&b}return!1};b.onScreenAndVisible=function(b,c){b=b||d();c=a.isFiniteNumber(c)?c:0;if(b instanceof d||b.jquery){if(!b.is(":visible"))return!1;b=b[0].getBoundingClientRect();return b.top>=0-c&&b.left>=0-c&&b.bottom<=d(m).height()+c&&b.right<=d(m).width()+c}return!1};b.compositeEventWrapper=function(a,e,d){var l=a;d&&(l=b.throttle(l,d,{trailing:!1}));return c.jsGuard(function(a){a&&(l(a),e&&a.$event&&a.$event.preventDefault())})};b.freeze=function(a){return"undefined"!==
typeof Object&&"function"===typeof Object.freeze?Object.freeze(a):a};b.isFrozen=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.isFrozen?Object.isFrozen(a):!1};return b});"use strict";g.when("jQuery").register("cr-jQuery",function(b){return b});"use strict";g.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",
UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",
SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",AJAX_POST:"reviews:ajax-post",SCROLL_TO_ELEMENT_CLICK:"reviews:scroll-to-element:click",OPEN_MASH_MODAL:"reviews:open-mash-modal",FILTER_APPLY:"reviews:filter-action:apply",FILTER_CHANGE:"reviews:filter-action:change",FILTER_TAB_CLICKED:"reviews:filter-action:tab-clicked",FILTER_APPLY_BEGIN:"reviews:filter-action:apply-begin",FILTER_APPLY_SUCCESS:"reviews:filter-action:apply-success",
FILTER_APPLY_ERROR:"reviews:filter-action:apply-error",FILTER_APPLY_DONE:"reviews:filter-action:apply-done",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",
INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click",TRIGGER_WEBLAB:"reviews:trigger-weblab",REFTAG_TRIGGER:"reviews:trigger-reftag"},filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",
TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews",MEDIA_KEY:"mediaType",ALL_CONTENTS:"all_contents",MEDIA_ONLY:"media_reviews_only",LANGUAGE_KEY:"filterByLanguage",HEIGHT_KEY:"filterByHeight",WEIGHT_KEY:"filterByWeight"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",
NOWRAP:"aok-nowrap"}});"use strict";g.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,d,c){function a(a){var h={};a&&a.data&&(h=a.data);var p=d.defaultIfBlank(h.url,a.$target.find("a").andSelf().filter("a").attr("href")),k=d.defaultIfBlank(h.title,"CustomerReviews"),k=""+k,l="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(a,b){a=d.defaultIfBlank(h[b],a);l+=b+"\x3d"+a+","});var l=l.slice(0,-1),f=null;try{(f=m.open(p,k,l))?
f.focus():c.logError("Unable to move focus to popup window with data: "+d.stringify(h),"ERROR"),a.$event.preventDefault()}catch(q){c.logError("Unable to open window with parameters: "+d.stringify(h),"FATAL",q)}return f}b.declarative("cr-popup",["click"],c.jsGuard(a));return{popup:a}});"use strict";g.when("A","cr-jQuery","reviews-constants","cr-ajax-model","cr-string-utils","cr-global-view").register("cr-generic-declarative-actions",function(b,d,c,a,e,h){function p(a){f(a)&&a.data.selector&&a.data.cssClass&&
(d(a.data.selector).toggleClass(a.data.cssClass),a.$event.preventDefault(),b.trigger("a:pageUpdate"))}function k(a){f(a)&&a.data.scrollToSelector&&(h.scrollTo(a.data.scrollToSelector,0),a.$event.preventDefault())}function l(c){if(f(c)&&c.data.url&&c.data.params){c.$event.preventDefault();b.declarative.remove(c.$currentTarget,r.AJAX_POST);c=c.data;var e=c.params,h=d(c.indicatorSelector)[0],k=q(d.fn.hide,c.hideOnSuccessSelector),l=q(d.fn.show,c.showOnFailureSelector);d(c.removeOnLoadSelector).remove();
a.post(c.url,{params:e,indicator:h,success:k,error:l})}}function f(a){return a&&a.data&&a.$event&&"function"===typeof a.$event.preventDefault}function q(a,b){if(b&&"function"===typeof a)return function(){var c=d(b);0<c.length&&a.call(c)}}var r=c.events;b.declarative(r.TOGGLE_CLASS_CLICK,"click",p);b.declarative(r.SCROLL_TO_ELEMENT_CLICK,"click",k);b.declarative(r.AJAX_POST,"click",l);return{toggleCssClass:p,scrollToElement:k,ajaxPost:l}});"use strict";g.register("cr-global-model",function(){return{generateUrl:function(b,
d){b&&"/"!==b.charAt(b.length-1)&&(b+="/");b&&d&&(b=b+"ref\x3d"+d);return b}}});"use strict";g.when("A","a-expander","cr-jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,d,c,a,e){function h(a){var b="";if(a&&a.closest!==n){var c=a.closest("*["+f.REFTAG+"]");c&&(b=c.attr(f.REFTAG))}e.isBlank(b)&&a&&a.closest!==n&&(a=a.closest("*[rel]"))&&(b=a.attr("rel"));return e.defaultIfBlank(b,"cm_cr_unknown")}function p(a){return a&&"function"===typeof a.is?a.is("*["+f.getReviews.CHECKED+
"]")&&a.is("*["+f.getReviews.UNCHECKED+"]"):!1}function k(a){return a&&a.has!==n&&a.is!==n?0<a.find(":checked").length||a.is(":checked"):!1}function l(a,b){return a&&a.attr!==n&&b?e.parseJSON(a.attr(b))||{}:{}}var f=a.data;b.on("a:pageUpdate",function(){d!==n&&d.initializeExpanders()});b.on(a.events.RELOAD_COMPLETE,function(){b.trigger("a:image:lazyLoad")});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(f.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),e;c&&a&&a.closest!==
n&&(e=a.closest(c));return p(e)?k(e)?l(e,f.getReviews.CHECKED):l(e,f.getReviews.UNCHECKED):l(e,f.getReviews.STANDARD)},getReftag:function(a){var b;a&&a.$target&&(b=a.$target);a&&a.id&&(b=c("#"+a.id));a&&a.expander&&a.expander.$expander&&(b=a.expander.$expander);b=h(b);"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:h,scrollTo:function(a,b){a=c(a).offset();b=b||0;var e=c("#cr-state-object").data("state"),e=e!==n&&e.disableScroll;a&&a.top!==n&&!e&&(c("html,body").stop(),
c("html,body").animate({scrollTop:a.top-b},{queue:!1,duration:500}))}}});"use strict";g.when("cr-A","cr-jQuery","cr-lazy-widget-model","cr-lazy-widget-view","cr-log-utils","cr-number-utils","cr-string-utils","cr-uri-utils","ready").register("cr-lazy-widget-controller",function(b,d,c,a,e,h,p,k){function l(d){var f=b.getValueFromState("lazyWidgetDomainWhitelist"),h=k.getCurrentHostname();if(f)b:{for(var l=0;l<f.length;l++)if(p.endsWith(h,f[l])){e.logCount("LazyWidgetInvalidDomain",0);break b}e.logError("AJAX triggered from invalid domain: "+
h,"WARN");e.logCount("LazyWidgetInvalidDomain",1)}else e.logCount("LazyWidgetInvalidDomain",1),e.logError("AJAX triggered with null whitelist from domain: "+h,"WARN");c.loadLazyWidgets(a.getLazyWidgetStubs())&&(e.logCount("LazyWidgetTrigger",1),e.logCount("LazyWidgetTrigger:"+d,1))}var f={};f.bufferPixels=h.convertToInteger(b.getValueFromState("lazyWidgetLoaderBufferPixels"),1E3);f.delayBeforeTriggering=h.convertToInteger(b.getValueFromState("lazyWidgetLoaderDelayBeforeTriggering"),5E3);f.triggerLazyLoadIfWidgetWithinBuffer=
function(e){c.lazyLoadHasTriggered()||a.getLazyWidgetStubs().each(function(a,c){if(b.onScreen(d(c),f.bufferPixels))return l("scroll"),b.off("scroll",f.triggerLazyLoadIfWidgetWithinBuffer),!1})};var q={};f.logVisibleStubMetrics=function(c){a.getLazyWidgetStubs().each(function(a,c){a=d(c);c=a.data("widget-name");!q[c]&&b.onScreen(a)&&(e.logCount("VisibleLazyWidgetStub",1),e.logCount("VisibleLazyWidgetStub:"+c,1),q[c]=!0)})};b.on("scroll",f.logVisibleStubMetrics);b.on("scroll",f.triggerLazyLoadIfWidgetWithinBuffer);
d(a.getHoverTargets()).mouseenter(function(){l("hover")});e.logCount("LazyWidgetTrigger",0);return b.freeze(f)});"use strict";g.when("cr-A","cr-ajax-model","cr-uri-utils","ready").register("cr-lazy-widget-model",function(b,d,c){var a={},e=b.getValueFromState("lazyWidgetLoaderUrl"),h=!1;a.loadLazyWidgets=function(a){if(!h&&0<a.length){h=!0;var k=b.getValueFromState("asin"),l=b.getValueFromState("lazyWidgetCsrfToken"),f=b.getValueFromState("languageOfPreference");a=b.reduce(a,function(a,c){return a+
"\x26lazyWidget\x3d"+b.$(c).data("widget-name")},e+"?asin\x3d"+k+"\x26csrf\x3d"+l+"\x26language\x3d"+f);d.postWithoutFatals(a,{success:u,cache:!1,headers:{"cache-control":"no-cache"},params:c.getUrlParametersMap()||{}});return!0}return!1};a.lazyLoadHasTriggered=function(){return h};return b.freeze(a)});"use strict";g.when("cr-A","cr-jQuery","ready").register("cr-lazy-widget-view",function(b,d){var c={},a=b.getValueFromState("lazyWidgetLoaderHoverTargetsSelector")||"";c.getLazyWidgetStubs=function(){return d(".cr-lazy-widget")};
c.getHoverTargets=function(){d(a)};return b.freeze(c)});"use strict";g.when("A").register("cr-log-utils",function(b){function d(a,b,c){m.ueLogError&&("string"!==typeof b&&(b="FATAL"),c?m.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):m.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function c(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:d,jsGuard:function(a){if("function"===typeof a)return function(){try{return a.apply(this,
arguments)}catch(b){d("Uncaught Error in function","FATAL",b)}};d("Unable to wrap non-function","ERROR");return a},incrementCount:function(a,b){m.ue&&(a=c(a,b),b=m.ue.count(a)||0,m.ue.count(a,b+1))},logCount:function(a,b,d){m.ue&&(a=c(a,d),m.ue.count(a,b))}}});"use strict";g.when("A","reviews-constants").register("cr-mash-utils",function(b,d){function c(a){g.when("mash").execute(function(b){b.navstack.begin().modalOpen(a).end()})}var a=!1;g.when("mash").execute(function(){a=!0});b.declarative(d.events.OPEN_MASH_MODAL,
"click",function(a){c(a.data.url);a.$event.preventDefault()});return{isMash:function(){return a},openModal:c}});"use strict";g.when("A","cr-log-utils").register("cr-number-utils",function(b,d){return{convertToInteger:function(b,a){if(b===parseInt(b,10))return b;if(null!==b&&b!==n&&""!==b)return parseInt(b.replace(/[^0-9]/g,""),10);if(a!==n)return a;d.logError("convertToInteger","Cannot convert "+b+" to Integer");return 0},isFiniteNumber:function(b){return"number"===typeof b&&!isNaN(b)&&isFinite(b)}}});
"use strict";g.when("cr-A","reviews-constants","cr-ajax-model","cr-global-model").register("cr-reftag-utils",function(b,d,c,a){function e(a){c.postWithoutFatals(a)}b.declarative(d.events.REFTAG_TRIGGER,"click",function(a){a.data.refMarker&&a.data.reftagTriggerUrl&&e(a.data.reftagTriggerUrl+"/ref\x3d"+a.data.refMarker)});return{triggerRefTagWithUrl:e,triggerRefTag:function(c){var d=b.getValueFromState("reftagTriggerUrl");d&&c&&e(a.generateUrl(d,c))}}});"use strict";g.when("A","cr-jQuery").register("cr-streaming-utils",
function(b,d){return{appendFadeIn:function(c){if(null!==c&&2<c.length&&null!==c[1]&&null!==c[2]){var a=c[1];c=d(c[2]).hide();d(a).append(c);b.fadeIn(c,500,"ease-in-out",function(){})}},replace:function(b){if(null!==b&&2<b.length&&null!==b[1]&&null!==b[2]){var a=b[2];d(b[1]).replaceWith(d(a))}}}});"use strict";g.when("A","cr-log-utils").register("cr-string-utils",function(b,d){function c(a){return null===a||a===n?!0:0===b.trim(a).length}return{defaultIfBlank:function(a,b){return c(a)?b:a},isBlank:c,
parseJSON:function(a){try{return b.parseJSON(a)}catch(c){d.logError("Unable to parse JSON object","ERROR",c)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},endsWith:function(a,b){if(a===b)return!0;if(null===a||null===b)return!1;var c=a.lastIndexOf(b);return-1!==c&&c===a.length-b.length},stringify:function(a){return m.JSON&&m.JSON.stringify?m.JSON.stringify(a):a}}});"use strict";g.when("A").register("cr-uri-utils",function(b){function d(){return m.location.hostname}
function c(a){a=a||m.location.href;var c={},d=a.indexOf("?"),g=a.indexOf("#");a=a.slice(d+1,g>d?g:n)||"";d=[];-1<a.indexOf("\x26")?d=a.split("\x26"):-1<a.indexOf("\x3d")&&(d=[a]);b.each(d,function(a,b){0<a.indexOf("\x3d")&&(a=a.split("\x3d"),c[a[0]]=a[1])});return c}return{getUrlParametersMap:c,addKeyValuePair:function(a,b,d){d=d||0;if(c(a)[b]===d||!a||!b)return a;b="?"+b+"\x3d"+d;return-1<a.indexOf("?")?a.replace("?",b+"\x26"):a+b},getCurrentHostname:d,getDomainRealmBaseUrl:function(a){a=a||d();
if(-1!==a.indexOf(".corp.amazon.com"))return"https://development.amazon.com/";if(-1!==a.indexOf(".proxy.amazon.com")){a=a.split(".")[1];var b={dub:"https://pre-prod.amazon.co.uk/",pdx:"https://pre-prod.amazon.co.jp/",pek:"https://pre-prod.amazon.cn/"};return b[a]!==n?b[a]:"https://pre-prod.amazon.com/"}return"/"}}});"use strict";g.when("A","reviews-constants").register("cr-weblab-utils",function(b,d){function c(a){m.ue&&m.ue.trigger&&m.ue.trigger(a.weblabID,a.treatment)}b.declarative(d.events.TRIGGER_WEBLAB,
"click",function(a){a.data.weblab&&a.data.treatment&&c({weblabID:a.data.weblab,treatment:a.data.treatment})});return{triggerWeblab:c}});"use strict";g.when("cr-A","cr-jQuery","cr-string-utils","cr-weblab-utils","afterReady").register("cr-weblab-on-view-utils",function(b,d,c,a){function e(a,c,e){k[c]||(a=h(d(a),c,e)(),l[c]=(l[c]||[]).concat(a),b.on.scroll(a))}function h(a,c,d){return function t(){b.inView(a)&&(g(c,d),b.each(l[c]||[],function(a){b.off("scroll",a)}));return t}}function g(b,c){k[b]||
(k[b]=!0,a.triggerWeblab({weblabID:b,treatment:c}))}var k={},l={};b.each(d("*[data-cr-weblab-trigger-on-scroll]"),function(a,b){a=d(a);var k=a.attr("data-cr-weblab-trigger-on-scroll"),k=c.parseJSON(k);null!==k&&(b="cr-weblab-trigger-on-scroll-"+b,a.addClass(b),e("."+b,k.weblabId,k.treatment))});return{triggerOnScrollIntoView:e,triggerWeblab:g}});"use strict";g.when("A","cr-uri-utils","cr-string-utils","3p-urijs","cr-jQuery").register("cr-extended-uri-utils",function(b,d,c,a,e){function h(){return a(m.location.href)}
function g(){return h().query()}return e.extend(d,{getCurrentUri:h,getCurrentQueryString:g,getCurrentQueryParameters:function(){return a.parseQuery(g())},isAmazonDomain:function(b){if("string"===typeof b||b instanceof String)b=a(b);var d=c.startsWith(b.domain(),"amazon");!1===d&&(b=b.hostname(),b=b.substring(b.indexOf(".")+1),d=c.startsWith(b,"amazon"));return d},setQueryParameters:function(d,e){if("string"===typeof d||d instanceof String)d=a(d);b.each(e,function(a,b){c.isBlank(a)?d.removeSearch(b):
d=d.setSearch(b,a)});return d},setReftag:function(b,d){if("string"===typeof b||b instanceof String)b=a(b);for(var e=b.segment(),g=!1,h=e.length-1;0<=h;h--)if(c.startsWith(e[h],"ref\x3d")){g=!0;e[h]="ref\x3d"+d;break}g||e.push("ref\x3d"+d);b.segment(e);return b}})});"use strict";g.when("A","cr-jQuery").register("histogram-trigger",function(b,d){function c(){b.onScreen(d("#histogramTable"))&&b.trigger("scroll")}b.on.afterLoad(c);return{triggerHistogram:c}})});
/* ******** */
(function(a){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,c=d?d("CustomerReviewsMedleyAssets",""):b;c.guardFatal?c.guardFatal(a)(c,window):c.execute(function(){a(c,window)})})(function(a,b,d){a.when("A","reviews-constants","medley-twister-view","medley-twister-model","ready").register("medley-twister-controller",function(c,k,e,a){function b(b){b=a.getASIN();var f=e.getDisplayedASIN();f&&b!==f&&(e.fadeReviews(!0),a.getReviews(f,function(){a.setASIN(f)},function(){},function(){e.fadeReviews(!1);
c.trigger(k.events.RELOAD_COMPLETE)}))}var d=e.getLoadedASIN();a.setASIN(d);c.on("a:pageUpdate",b);return{onTwist:b}});"use strict";a.when("A","cr-jQuery").register("medley-twister-view",function(a,b){return{getDisplayedASIN:function(){return String(b("#ASIN").val()||"")},getLoadedASIN:function(){return(b("#cr-state-object").data("state")||{}).asin||""},fadeReviews:function(a){!1===a?b("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",1):b("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",
.5)}}});"use strict";a.when("A","cr-global-model","cr-ajax-model","cr-uri-utils","cr-jQuery").register("medley-twister-model",function(b,a,e,d,l){function c(b){var a=d.getUrlParametersMap()||{};a.asin=b;return a}var h;return{setASIN:function(a){h=a||""},getASIN:function(){return h},getReviews:function(a,b,d,g){var f=l("#cr-state-object").data("state");"string"===typeof a&&10===a.length?e.post(f.medleyReviewsAjaxUrl,{params:c(a),attribution:"getMedleyReviews",success:b,error:d,finallyCallback:g}):
"function"===typeof g&&g()}}})});
/* ******** */
(function(f){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,c=k?k("CustomerReviewsVotingAssets",""):h;c.guardFatal?c.guardFatal(f)(c,window):c.execute(function(){f(c,window)})})(function(f,h,k){f.when("A","vote-model-v2","vote-view","a-modal","cr-log-utils").register("vote-controller-v2",function(c,b,a,l,f){function h(e,d){m(e,d);a.showElementByCssSelector(e,d.inFlight)}function m(e,d){a.hideElementByCssSelector(e,d.hideVoteComponents);d.hideAbuseComponents&&a.hideElementByCssSelector(e,
d.hideAbuseComponents)}function k(e,d){d.isReportAbuse&&(e=c.$("#mobile-abuse-"+d.reviewId),l.get(e).hide());h(e,d.cssSelectors);b.submitVote(d,function(g){if(!0===g){g=e;var b=d.cssSelectors;m(g,b);a.showElementByCssSelector(g,b.onSuccess)}else g=e,b=d.cssSelectors,m(g,b),a.showElementByCssSelector(g,b.onError)},function(b){if(401===b.http.status){if(b.http.getResponseHeader("x-amz-re-authentication-url")){f.logCount("Ajax401WithReAuthUrl:SubmitVote",1);return}f.logCount("Ajax401WithoutReAuthUrl:SubmitVote",
1)}b=e;var c=d.cssSelectors;m(b,c);a.showElementByCssSelector(b,c.onError)})}c.declarative("reviews:vote-action","click",function(a){k(a.$target,a.data);a.$event.preventDefault()});return{submitVote:k}});"use strict";f.when("A","cr-ajax-model").register("vote-model-v2",function(c,b){return{submitVote:function(a,c,f){var l={"anti-csrftoken-a2z":a.csrfT};a.physicalId&&a.imageExtension&&(l["x-amz-extra-params"]=[a.physicalId,a.imageExtension]);b.post(a.ajaxUrl,{params:{reviewId:a.reviewId},attribution:"submitVote",
success:c,error:f,headers:l})}}});"use strict";f.when("A").register("vote-view",function(c){function b(a,b){return a.closest(".cr-vote").find(b)}return{hideThankYouAlert:function(a){b(a,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(a){b(a,".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(a){b(a,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(a){b(a,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(a){b(a,".cr-vote-feedback").addClass("aok-hidden")},
hideButtons:function(a){b(a,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(a,c){b(a,c).addClass("aok-hidden")},showElementByCssSelector:function(a,c){b(a,c).removeClass("aok-hidden")}}})});
/* ******** */
(function(e){var v=window.AmazonUIPageJS||window.P,u=v._namespace||v.attributeErrors,c=u?u("CustomerReviewsGalleryAssets",""):v;c.guardFatal?c.guardFatal(e)(c,window):c.execute(function(){e(c,window)})})(function(e,v,u){e.when("A","cr-jQuery","cr-log-utils","reviews-constants","review-image-assets-loaded").register("review-image-binder",function(c,b,g,m){function k(a,q,f,h,d){if(!(a&&q&&f instanceof b&&h instanceof b&&d instanceof b))return g.logError("Invalid parameters for imageBinder.initializeEventHandlers with ASIN: "+
a+", galleryName: "+q+", $popoverTrigger: "+f+", $thumbnails: "+h+", $galleryLink: "+d,"FATAL"),!1;var c="reviewsLightbox-ready-"+q;h.click(function(){l(a,q);var d=h.index(this);f.click();e.when(c).execute(function(){b("#"+q).trigger("jumpToImageAtIndex",d)})});d.click(function(){l(a,q);f.click();e.when(c).execute(function(){b("#"+q).trigger("hideImmersiveView")})});return!0}function l(b,d){if(!b||!d)return g.logError("Invalid parameters for imageBinder.initializeImageGallery with ASIN: "+b+", galleryName: "+
d,"FATAL"),!1;if(n)return!0;(new ReviewsLightbox(d,"DESKTOP")).initializeForAsin(b);return n=!0}var n=!1,d={};e.when("reviewsLightbox-js").execute(function(){var a=b("#reviews-image-gallery-container"),d=a.attr("data-asin");0<a.length&&d&&k(d,"reviews-image-gallery",a.find(".a-popover-trigger"),a.find(".review-image-tile"),a.find(".reviews-image-gallery-link"))});c.on(m.events.RELOAD_COMPLETE,function(){d={}});return{bindReview:function(a,c,f){var h=new ReviewGallery(f,"DESKTOP"),g=b("#"+c);g.find(".review-image-tile").each(function(c){b(this).click(function(){d[a]||
(h.initializeForReview(a),d[a]=!0);g.find(".a-popover-trigger").click();e.when("reviewsLightbox-ready-"+f).execute(function(){h.render();h.showImageAtIndex(c)})})})},initializeImageGallery:l,initializeEventHandlers:k}});"use strict";e.when("A","cr-jQuery","cr-image-popover-data-fetcher","cr-see-all-images-controller").register("cr-image-popover-controller",function(c,b,g,m){function k(){for(var a=0;a<w.length;a++)a!=t&&(b(w[a]).unbind("click"),b(w[a]).removeClass("cr-lightbox-selected")),b(w[a]).click(l(a))}
function l(b){return function(){a(b)}}function n(){b(u).unbind("click");b(A).unbind("click");b(u).click(function(){var b=parseInt(t,10)+1;a(b);d()});b(A).click(function(){var b=parseInt(t,10)-1;a(b);d()});b(G).mouseenter(function(){d()}).mouseleave(function(){H.animate({opacity:0},100);v.animate({opacity:0},100)})}function d(){var a=.25,f=.25;b(u).css("cursor","pointer");b(A).css("cursor","pointer");var d=g.getReviewIds();if(!x&&t===r.length-1||x&&t===r.length-1&&d.indexOf(B)==d.length-1)a=0,b(u).css("cursor",
"auto");d=g.getReviewIds();if(!x&&0===t||x&&0===t&&0==d.indexOf(B))f=0,b(A).css("cursor","auto");H.animate({opacity:a},100);v.animate({opacity:f},100)}function a(a){if(0<=a&&a<r.length)C.attr("src",r[a]),b(w[t]).removeClass("cr-lightbox-selected"),b(w[a]).addClass("cr-lightbox-selected"),t=a;else if(x){var f=g.getReviewList(),d=g.getReviewIds(),c=d.indexOf(B),q={popover:{$trigger:{context:{}}}};a>t?(c++,c<d.length&&(q.popover.$trigger.context.id=d[c]+"-0",h(q))):(c--,-1<c&&(q.popover.$trigger.context.id=
d[c]+"-"+(f[d[c]].images.length-1),h(q)))}}function q(a){b(D).empty();a.forEach(function(a,d){d===t?b(D).append('\x3cimg src\x3d"'+a+'" class\x3d"cr-lightbox-image-thumbnail cr-lightbox-selected" /\x3e'):b(D).append('\x3cimg src\x3d"'+a+'" class\x3d"cr-lightbox-image-thumbnail"/\x3e')});w=p.find(".cr-lightbox-image-thumbnail");k()}function f(d,f,c,h){p=(x=h||!1)?b("#cr_customers_image_gallery"):b("#"+d+"_image_popover");H=p.find(".cr-lightbox-navigator-button__next");v=p.find(".cr-lightbox-navigator-button__back");
u=p.find(".cr-lightbox-navigator-container__next");A=p.find(".cr-lightbox-navigator-container__back");w=p.find(".cr-lightbox-image-thumbnail");G=p.find(".cr-lightbox-image-viewer");C=G.find(".cr-lightbox-main-image");K=p.find(".cr-lightbox-review-title");L=p.find(".cr-lightbox-review-body");M=p.find(".cr-lightbox-review-origin");E=p.find(".cr-lightbox-review-rating");D=p.find(".cr-lightbox-image-thumbnails");x&&(F=p.find(".cr-lightbox-customer-profile"),N=p.find(".cr-lightbox-customer-profile .a-profile-name"),
O=p.find(".cr-lightbox-customer-profile .a-profile-avatar \x3e img"),I=E.find(".a-icon-alt"));r=f;"string"===typeof f&&(r=f.substring(1,f.length-1).split(","));k();a(y(c).thumbnailId||0);n()}function h(a){var b=g.getReviewList();g.getReviewIds();for(var d=y(a).reviewId,c=[],h=[],l=0;l<b[d].images.length;l++)c.push(b[d].images[l].source),h.push(b[d].images[l].lowResSource);B=d;f(d,c,a,!0);a=B;K.text(b[a].title);E.removeClass();E.addClass("a-icon a-icon-star a-star-"+b[a].starRating+" cr-lightbox-review-rating");
I.text(I.text().replace(/\d([.,]\d)?/,b[a].starRating+".0"));q(h);L.text(b[a].reviewText);M.text(b[a].originDescription);x&&(b=b[a],null===b.customerProfileLink||0===b.customerProfileLink.length?F.css("cursor","initial"):F.css("cursor",""),F.attr("href",b.customerProfileLink),N.text(b.customerName),O.attr("src",b.customerProfileImage));z(!1)}function y(a){return a&&a.popover&&a.popover.$trigger&&a.popover.$trigger.context&&(a=a.popover.$trigger.context.id)&&(a=a.split("-"),1<a.length)?{reviewId:a[0],
thumbnailId:parseInt(a[1],10),seeAllImages:!1}:{seeAllImages:!0}}function e(a){y(a).seeAllImages?z(!0):h(a)}function z(a){p=b("#cr_customers_image_gallery");a?(p.hide(),J.show(),m.updateSeeAllImages(J,h),C&&C.attr("src","")):(p.show(),J.hide(),R.hide(),S.show(),P.removeClass("cr-lightbox-review-row-no-display"),P.addClass("cr-lightbox-review-row"))}var r,t=0,H,v,u,A,w,G,C,B,x=!1,Q=!1,K,L,M,E,D,F,N,O,I,J=b("#seeAllImagesContainer"),p=b("#cr_customers_image_gallery"),R=b(".cr-large-loadingIcon"),P=
b("#crReviewRow"),S=b("#crViewAllImagesLink");return{initImagePopover:f,loadDataAndInitImageGalleryPopover:function(a,b,d,f){g.isDataLoaded()?e(a):g.fetchData(d,b,f,function(b,f){if(b=!Q)a:{b=g.getReviewIds();for(f=0;f<d.length;f++)if(0>b.indexOf(d[f])){b=!1;break a}b=!0}b&&(e(a),Q=!0)})},toggleSeeAllView:z}});"use strict";e.when("A","cr-jQuery","cr-log-utils").register("cr-image-popover-data-fetcher",function(c,b,g){function m(a,b,d){a="/hz/reviews-render/get-reviews-with-media?mediaType\x3dimage\x26asin\x3d"+
a+"\x26csrfToken\x3d"+b;d!==u&&(a+="\x26nextToken\x3d"+d);return a}function k(a,b,h,y,e,z){h=m(b,h,z);c.ajax(h,{method:"get",success:function(f){for(var c in f.reviewsWithMediaList)d[c]=f.reviewsWithMediaList[c];c=Object.keys(d);n=a.slice();for(var h=0;h<c.length;h++)0>a.indexOf(c[h])&&n.push(c[h]);"function"===typeof y&&y(d,n);f.nextToken?k(a,b,f.csrfToken,y,e,f.nextToken):l=!0},error:function(a){g.logCount("ReviewWithImages-DataFetcher-Error");"function"===typeof e&&e()}})}var l=!1,n=[],d={},a=
null;return{fetchData:k,getReviewList:function(){return d},getReviewIds:function(){return n},isDataLoaded:function(){return l},getCustomerImageAltText:function(){a||(a=b(".review-with-images-section .cr-customer-image-thumbnail")[0].getAttribute("alt"));return a}}});"use strict";e.when("A","cr-jQuery","cr-image-popover-data-fetcher").register("cr-see-all-images-controller",function(c,b,g){function m(a,d,f,c){a=b("\x3cdiv\x3e",{class:"cr-thumbnail-preview-tile",css:{background:"url("+a+") 50% 50% no-repeat"},
role:"img",alt:g.getCustomerImageAltText()});a.click(function(){c({popover:{$trigger:{context:{id:d+"-"+f}}}})});return a}function e(a,b,f){for(var c=g.getReviewList(),e=g.getReviewIds(),q=l;l<q+f;){var k=e[d];if(k&&c[k]){d++;for(var r=0;r<c[k].images.length;r++){var t="undefined"===typeof n[k+r]?!0:!1;t&&(a.append(m(c[k].images[r].lowResSource,k,r,b)),l++,0==l%7&&a.append("\x3cbr /\x3e"),n[k+r]=k+r)}}else break}}var l=0,n={},d=0;return{updateSeeAllImages:function(a,b){e(a,b,50);var d=0;a.scroll(function(){var f=
a.scrollTop();200<f-d&&(d=f,e(a,b,50))})}}});"use strict";e.when("A","cr-media-gallery-view","cr-jQuery").register("cr-media-gallery-controller",function(c,b,g){function m(){return 480<g(v).width()?3:2}function e(){var d=b.getCurrentMasonryItems(),a=m();0<d.length&&(d=b.getPreciseMaxMasonryListHeightItems(d,a),b.setMasonryListHeight(d.heightInPixelOfColumn,"px",d.nItemInColumn*l))}c.on("resize",function(){b.isMediaGalleryPageVisible()?e():n=!0});var l=8,n=!1;return{initialize:e,getNoOfColumns:m,initializeAfterPopoverHide:function(){n&&
e();n=!1}}});"use strict";e.when("A","cr-jQuery").register("cr-media-gallery-view",function(c,b){function g(){c.objectIsEmpty(k)&&(k=b(".cr-mg-masonry-list-height-control"));return k}var e=null,k=null;return{getCurrentMasonryItems:function(){c.objectIsEmpty(e)&&(e=b(".cr-mg-masonry-list"));return e.find(".cr-mg-masonry-item")},setMasonryListHeight:function(b,c,d){var a=g().get(0);a&&(a.style.setProperty("--height-to-column-width",b+c),a.style.setProperty("--height-in-pixel",d+"px"))},getPreciseMaxMasonryListHeightItems:function(c,
e){for(var d=Array(e),a=Array(e),g=0;g<e;g++)d[g]=0,a[g]=0;var f=0;c.each(function(){var c=b(this).children(".cr-mg-ratio-control");d[f%e]+=c.get(0).getBoundingClientRect().height;a[f%e]+=1;f++});c=d.indexOf(Math.max.apply(Math,d));return{heightInPixelOfColumn:d[c],nItemInColumn:a[c]}},isMediaGalleryPageVisible:function(){var b=g();return b?b.is(":visible"):!1}}});"use strict";e.when("A","cr-jQuery").register("cr-review-inline-images-controller",function(c,b){function e(c){return b("#%s-cr-inline-images-preview".replace("%s",
c)).find(".cr-review-inline-images-main-image")}c.declarative("cr-review-inline-images-thumbnail-click","click",function(b){var c=b.data.imageSrc;e(b.data.reviewId).attr("src",c)});return{getMainImage:e,getAllThumbnails:function(c){return b("#%s-cr-inline-images-preview".replace("%s",c)).find(".cr-review-inline-images-thumbnails .cr-review-inline-images-thumbnail")}}});"use strict";e.when("cr-inline-videos-controller","ready").register("cr-inline-videos-module",function(c){c.initialize(!0)});"use strict";
e.when("A","reviews-constants","cr-log-utils","cr-inline-videos-view","cr-vse-brila-player-gateway").register("cr-inline-videos-controller",function(c,b,e,m,k){function g(b){m.getPlayerPlaceholders().each(function(f,e){f=c.$(e);if(!m.isPlayerRequestPending(f)&&(!b||b&&m.isPlayerPlaceholderInViewport(f))){m.markPlayerRequestAsPending(f);e=m.extractVideoAsset(f);var g=c.$("#cr-state-object").data("state");e={videoUrl:e.videoUrl,thumbnailUrl:e.thumbnailUrl,reviewId:e.reviewId,closedCaptions:e.closedCaptions,
vseContentId:e.vseContentId,marketplaceId:g.marketplaceId,locale:g.locale,page:g.page||"cr_page",placement:g.page?g.page+"_cr_inline_review":"cr_inline_review"};k.getVideoPlayer("vse_reviews_desktop_"+e.reviewId+"_"+c.now(),e,n(e),d(f),a(f))}})}function n(a){return!c.objectIsEmpty(a)&&!c.objectIsEmpty(a.vseContentId)&&""!=a.vseContentId}function d(a){return function(b){m.markPlayerRequestAsDone(a);m.renderPlayer(a,b)}}function a(a){return function(b){m.markPlayerRequestAsDone(a);m.showErrorMessage(a);
e.logError("Failed loading inline video player: "+JSON.stringify(b),"ERROR")}}function q(a){if(a)c.on(c.constants.BROWSER_EVENTS.SCROLL,function(){g(!0)});c.on(b.events.RELOAD_COMPLETE,function(){g(a)})}return{initialize:function(a){g(a);q(a)},fetchVideoPlayers:g}});"use strict";e.when("A").register("cr-inline-videos-view",function(c){return{getPlayerPlaceholders:function(){return c.$(".cr-video-desktop-placeholder")},extractVideoAsset:function(b){b=b.data();return{reviewId:b.reviewId,videoUrl:b.videoUrl,
thumbnailUrl:b.thumbnailUrl,closedCaptions:b.closedCaptions,vseContentId:b.vseContentId}},markPlayerRequestAsPending:function(b){b.data("playerRequestPending",!0)},markPlayerRequestAsDone:function(b){b.removeData("playerRequestPending");b.removeClass("cr-video-desktop-placeholder")},isPlayerRequestPending:function(b){b=b.data("playerRequestPending");return"undefined"!==b&&b},isPlayerPlaceholderInViewport:function(b){return c.onScreen(b,800)},renderPlayer:function(b,c){b.html(c)},showErrorMessage:function(b){b.addClass("cr-media-show-error-msg")}}});
"use strict";e.when("A","cr-uri-utils","cr-log-utils","cr-ajax-model").register("cr-vse-brila-player-gateway",function(c,b,g,m){function k(b,a,k){var d={requester:"vse_reviews_desktop",clientPrefix:b,marketplaceID:a.marketplaceId,locale:a.locale,page:a.page,placement:a.placement};k&&a.vseContentId?d.video={contentID:a.vseContentId,contentIDType:"VIDEO_ID"}:(a.videoUrl&&a.thumbnailUrl&&a.reviewId||g.logCount(l("vse_player:${placement}:incomplete_video_payload",a),1),d.video={videoURL:a.videoUrl,imageURL:a.thumbnailUrl,
contentID:a.reviewId,contentIDType:"EXTERNAL_VIDEO_ID"},c.objectIsEmpty(a.closedCaptions)||""==a.closedCaptions||(d.video.closedCaptions=a.closedCaptions));e.now("Brila").execute("vse-assets-check",function(a){a!==u&&(d.excludeAssets=["Brila","VSEPlayer"])});return d}function l(b,a){return b.replace("${placement}",a.placement)}var n=b.getDomainRealmBaseUrl()+"vap/ew/subcomponent/vseplayer";return{getVideoPlayer:function(b,a,e,f,h){var d=c.now();b={params:k(b,a,e),paramsFormat:"json",crossDomain:!0,
method:"post",contentType:"application/json",withCredentials:!0,timeout:4E3,success:function(b){var e=c.now()-d;g.logCount(l("vse_player:${placement}:load:status",a),1);g.logCount(l("vse_player:${placement}:load:request_time",a),e);"function"===typeof f&&f(b)},error:function(b){g.logCount(l("vse_player:${placement}:load:status",a),0);"function"===typeof h&&h(b)}};g.logCount(l("vse_player:${placement}:load:count",a),1);m.post(n,b,2)}}})});
/* ******** */
(function(g){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,e=p?p("CustomerReviewsFilteringAssets",""):m;e.guardFatal?e.guardFatal(g)(e,window):e.execute(function(){g(e,window)})})(function(g,m,p){g.when("cr-A","cr-jQuery","cr-filtering-view","cr-filtering-model","cr-global-view","reviews-constants","cr-streaming-utils").register("cr-filtering-controller",function(e,f,b,d,l,c,k){function h(n){var a=!1,c=!1;n.toggleFilters&&(c=!0);d.setASIN(b.getLoadedFilterParam("asin"));
a=d.setReviewerType(n.reviewerType,c)||a;a=d.setFormatType(n.formatType,c)||a;a=d.setFilterByKeyword(n.filterByKeyword,c)||a;a=d.setFilterByLanguage(n.filterByLanguage,c)||a;a=d.setSortOrder(n.sortOrder,c)||a;a=d.setStarFilter(n.filterByStar,c)||a;a=d.setPageNumber(n.pageNumber,c)||a;a=d.setHeightFilter(n.filterByHeight,c)||a;return a=d.setWeightFilter(n.filterByWeight,c)||a}function q(a){if(h(a.data)||a.data.forceReload)a.data.sortOrder&&b.setSortDropdown(a.data.sortOrder),b.hideReviewLoadError(),
b.hideReviews(),b.showLoadingSpinner(),e.trigger(c.events.FILTER_APPLY_BEGIN,a),d.getReviews(function(){b.showReviews();"filterByHeight"===d.getActiveTab()&&b.scrollToFilterIndex("filterByHeight");"filterByWeight"===d.getActiveTab()&&b.scrollToFilterIndex("filterByWeight");e.trigger(c.events.FILTER_APPLY_SUCCESS,a)},function(){b.showReviewLoadError();e.trigger(c.events.FILTER_APPLY_ERROR,a)},function(){b.hideLoadingSpinner();e.trigger(c.events.FILTER_APPLY_DONE,a);e.trigger(c.events.RELOAD_COMPLETE)},
function(a){"appendFadeIn"===a[0]?k.appendFadeIn(a):"replace"===a[0]&&k.replace(a)},l.getReftag(a)),a.data.scrollToSelector&&l.scrollTo(a.data.scrollToSelector,0)}function g(a){a&&a.data&&q(a)}function a(a){a&&a.data&&a.$target&&a.data.filterType&&(a.data[a.data.filterType]=a.$target.val(),q(a))}function r(a){a&&a.data&&a.data.filterType&&(b.deactivateFilterTabHeaders(),b.activateFilterTabHeader(a.data.filterType),b.changeFilterOptionsTo(a.data.filterType),d.setActiveTab(a.data.filterType),"filterByHeight"!==
a.data.filterType&&"filterByWeight"!==a.data.filterType||b.scrollToFilterIndex(a.data.filterType))}d.setReviewsAjaxUrl(b.getReviewsAjaxUrl());b.enableDesktopDPFilterDropdown();e.declarative(c.events.FILTER_APPLY,"click",e.compositeEventWrapper(g,!0,100));e.declarative(c.events.FILTER_CHANGE,"change",e.compositeEventWrapper(a,!0,100));e.declarative(c.events.FILTER_TAB_CLICKED,"click",r);d.setReviewerType(b.getLoadedFilterParam("reviewerType"),!1);d.setFormatType(b.getLoadedFilterParam("formatType"),
!1);d.setFilterByKeyword(b.getLoadedFilterParam("filterByKeyword"),!1);d.setFilterByLanguage(b.getLoadedFilterParam("filterByLanguage"),!1);d.setStarFilter(b.getLoadedFilterParam("filterByStar"),!1);d.setSortOrder(b.getLoadedFilterParam("sortOrder"),!1);d.setPageNumber(b.getLoadedFilterParam("pageNumber"),!1);d.setHeightFilter(b.getLoadedFilterParam("filterByHeight"),!1);d.setWeightFilter(b.getLoadedFilterParam("filterByWeight"),!1);d.setLanguage(b.getLoadedFilterParam("languageOfPreference"));b.getLoadedFilterParam("showLanguageFilter")?
d.setActiveTab("filterByLanguage"):b.getLoadedFilterParam("showHeightFilter")&&(d.setActiveTab("filterByHeight"),b.scrollToFilterIndex("filterByHeight"));return{setFilterParams:h,onFilterApply:g,onFilterChange:a,onFilterTabClicked:r}});"use strict";g.when("A","cr-ajax-model","ready").register("cr-filtering-model",function(e,f){function b(){return h.asin||""}function d(){return g||""}function l(a,c){c?h[a]=c:delete h[a]}function c(a,c,b){var d=!1;a&&c!==p&&(d=k(a)!==c,!d&&b&&(c="CLEAR_VALUE",d=!0),
l(a,c));return d}function k(a){return h[a]||""}var h={},g="",m;return{getReviews:function(a,c,b,d,l){var e=g;m&&f.abort(m);l&&(e+="ref\x3d"+l);m=f.post(e,{params:h,attribution:"getFilteredReviews",success:a,error:c,finallyCallback:function(){b();m=0},chunk:d})},setASIN:function(a){var c=b()!==a;l("asin",a);return c},getASIN:b,setReviewsAjaxUrl:function(a){var c=d()!==a;g=a||"";return c},getReviewsAjaxUrl:d,setReviewerType:function(a,b){return c("reviewerType",a,b)},getReviewerType:function(){return k("reviewerType")},
setFormatType:function(a,b){return c("formatType",a,b)},getFormatType:function(){return k("formatType")},setFilterByKeyword:function(a,b){return c("filterByKeyword",a,b)},getFilterByKeyword:function(){return k("filterByKeyword")},setFilterByLanguage:function(a,b){return c("filterByLanguage",a,b)},getFilterByLanguage:function(){return k("filterByLanguage")},setSortOrder:function(a,b){return c("sortBy",a,b)},getSortOrder:function(){return k("sortBy")},setStarFilter:function(a,b){return c("filterByStar",
a,b)},getStarFilter:function(){return k("filterByStar")},setPageNumber:function(a,b){return c("pageNumber",a,b)},getPageNumber:function(){return k("pageNumber")},setHeightFilter:function(a,b){return c("filterByHeight",a,b)},getHeightFilter:function(){return k("filterByHeight")},setWeightFilter:function(a,b){return c("filterByWeight",a,b)},getWeightFilter:function(){return k("filterByWeight")},getFilterParams:function(){return h||{}},updateFilterParam:l,setActiveTab:function(a){return l("activeTab",
a)},getActiveTab:function(){return k("activeTab")},setLanguage:function(a){return l("language",a)}}});"use strict";g.when("cr-A","cr-jQuery","a-dropdown","ready").register("cr-filtering-view",function(e,f,b){function d(b){return(f("#cr-state-object").data("state")||{})[b]||""}return{getReviewsAjaxUrl:function(){return(f("#cr-state-object").data("state")||{}).reviewsAjaxUrl||""},showLoadingSpinner:function(){var b=e.getValueFromState("onLoadShowHideElements");f(b).removeClass("aok-hidden")},hideLoadingSpinner:function(){var b=
e.getValueFromState("onLoadShowHideElements");f(b).addClass("aok-hidden")},hideReviews:function(){f(".filterable-reviews-content").addClass("aok-hidden")},showReviews:function(){f(".filterable-reviews-content").removeClass("aok-hidden")},showReviewLoadError:function(){f(".review-load-error").removeClass("aok-hidden")},hideReviewLoadError:function(){f(".review-load-error").addClass("aok-hidden")},deactivateFilterTabHeaders:function(){f(".cr-tab-header-text").removeClass("cr-tab-active")},activateFilterTabHeader:function(b){f(".cr-tab-header-text-"+
b).addClass("cr-tab-active")},changeFilterOptionsTo:function(b){f(".cr-tab-content").addClass("aok-hidden");f(".cr-tab-content-"+b).removeClass("aok-hidden")},getLoadedFilterParam:d,setSortDropdown:function(d){b.getSelect("cm-cr-sort-dropdown").setValue(d)},scrollToFilterIndex:function(b){var c;c=0;var e;e=d("isCardTreatmentEnabled")?f(".cr-horizontal-scroll-list-cardify-padding ul \x3e *:first-child"):f(".cr-horizontal-scroll-list-padding ul \x3e *:first-child");var h=f(m).width();b=f("ul#"+b+"-button-list")[0];
if(e===p||h===p||b===p)c=-1;else{var g=parseInt(b.dataset.index);e=parseInt(e.css("padding-left").replace("px",""));if(-1!==g){c=e-h/2;for(h=0;h<g;h++)c+=f("#"+b.children[h].firstElementChild.id).outerWidth(!0);c+=f("#"+b.children[g].firstElementChild.id).outerWidth(!0)/2}}0>c||f(".cr-filter-scroll-container").animate({scrollLeft:c},50)},enableDesktopDPFilterDropdown:function(){f("#cm-cr-dp-review-sort-type").removeClass("aok-hidden")}}});"use strict";g.when("cr-A","cr-lighthut-terms-view","reviews-constants",
"cr-log-utils").register("cr-lighthut-terms-controller",function(e,f,b,d){function g(b){b&&b.filterByKeyword!==p&&(f.setSelected(b.filterByKeyword),d.incrementCount("LighthutTermClicked"))}e.on(b.events.FILTER_APPLY_BEGIN,e.compositeEventWrapper(function(b){b&&b.data&&g(b.data)}));return{onFilterApplied:g}});"use strict";g.when("A","cr-jQuery","ready").register("cr-lighthut-terms-view",function(e,f){return{setSelected:function(b){b=b.replace(/ /g,"_");var d=(b=f("#cr-lighthouse-term-"+b))&&b.hasClass("cr-lighthut-term-selected");
f(".cr-lighthut-term-selected").removeClass("cr-lighthut-term-selected");d||b.addClass("cr-lighthut-term-selected")}}})});
/* ******** */
