'use strict';mix_d("P13NSCCards__p13n-desktop-carousel:p13n-desktop-carousel__zfO3h_w6","exports tslib @c/aui-carousel @c/dom @c/remote-operations @c/scoped-dom @p/A @p/a-carousel-framework @c/browser-operations @c/metrics @c/aui-modal @c/aui-untrusted-ajax @c/logger @c/aui-utils".split(" "),function(H,m,O,P,Q,R,S,T,U,B,V,W,X,Y){function v(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var Z=v(O),C=v(Q),t=v(R),z=v(S),aa=v(T),D=v(U),ba=v(B),ca=v(V),I=v(W),u=v(X),E=v(Y),F=function(a){B.count(a,
(B.count(a)||0)+1)},da=function(a){var c=Array.prototype.slice.call(a.querySelectorAll("[data-metrics]"));c.push(a);c.forEach(function(b){if(b&&b.dataset&&b.dataset.metrics){var d=JSON.parse(b.dataset.metrics),f;for(f in d)d.hasOwnProperty(f)&&B.count(f,d[f]);b.removeAttribute("data-metrics")}})},ea=function(){var a=t["default"].cardRoot.querySelector(".p13n-edit-your-recs-button"),c=t["default"].cardRoot.querySelector(".p13n-kebab-button-edit-recs-bottom-sheet");if(c&&a){var b=D["default"].setup();
ba["default"].count("mobile-carousel-card:p13nEditRecsBottomSheet:rendered",1);b.define("show-sheet","click",function(){F("mobile-carousel-card:p13nEditRecsBottomSheet:show");F("mobile-carousel-card:internal:p13nEditRecsBottomSheet:show")});b.attach("show-sheet",c);a.addEventListener("click",function(){F("mobile-carousel-card:p13nEditRecsBottomSheet:notInterested")})}},ha=function(a){return m.__awaiter(void 0,void 0,void 0,function(){var c,b,d,f,g;return m.__generator(this,function(e){c=t["default"].cardRoot.querySelector(".report-problem-modal-root");
if(!c)return[2];b={a11yOpenMessage:"A modal for internal users to report problems with recommendations",hideHeader:!1,width:560};d=ca["default"].create("report-flag-modal",".report-problem-modal-root",b);f=D["default"].setup();g=t["default"].cardRoot.querySelector(".report-flag");f.define("show","click",function(){d.show()});f.attach("show",g);fa(a,d);return[2]})})},fa=function(a,c){var b=t["default"].cardRoot.querySelector(".report-flag"),d=D["default"].setup();d.define("showFlag","mouseover",function(){b.classList.remove("report-flag-hide")});
d.define("hideFlag","mouseout",function(){b.classList.add("report-flag-hide")});d.attach("showFlag",a);d.attach("hideFlag",a);var f=t["default"].cardRoot.querySelector(".internal-flag-form");f.onsubmit=function(g){return ia(f,g,a)};z["default"].on("a:popover:hide:"+c.id,function(){f.reset();var g=f.querySelector(".internal-flag-form-end").nextSibling;g&&g.classList.contains("report-problem-message")&&(g.innerText="")})},ia=function(a,c,b){c.preventDefault();c=a.querySelector(".internal-flag-env-data").dataset;
var d=a.querySelector(".internal-flag-title-text").value,f=a.querySelector(".internal-flag-description").firstElementChild.value,g=a.querySelector(".internal-flag-alias").value,e=a.querySelector(".internal-flag-form-end");a=t["default"].cardRoot.querySelectorAll(".a-carousel-card");b=ja(b,a.length);d="Internal user reported issue '"+d+"' with widget: "+t["default"].cardRoot.querySelector(".a-carousel-heading").innerText;c=ka(a,b,f,g,c);I["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",
contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:"9c9c97c9-6f69-4dba-a55d-26045c6a3068",description:c,descriptionContentType:"text/amz-markdown-sim",extensions:{tt:{assignedGroup:"P13N Report a Problem CX",category:"Website",impact:5,item:"Report a Problem CX",type:"Personalization"}},tags:[{id:"internal-problem-generated"}],title:d}}).then(function(p){J(e,!0,p)}).catch(function(p){J(e,!1,p)});return!1},ja=function(a,c){if(!a.dataset.aCarouselOptions)return u["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions",
"ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var b=t["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");b=(Number(b.value)||1)-1;return a.map(function(d){return JSON.parse(d).id}).slice(b,b+c)},ka=function(a,c,b,d,f){for(var g="",e=0;e<a.length;e++){var p=a[e].querySelector(".a-dynamic-image");g+=(p?"![]("+p.src+")":"IMAGE MISSING")+"\nASIN: "+(c[e]?c[e]:"ASIN MISSING")+"\n\n"}return"**This SIM-T ticket is created by the 'Report a Problem' internal tool. To know more, here's its wiki: https://w.amazon.com/bin/view/Personalization/CoreRecommendations/Projects/Canaries/Report-a-Problem-UX-on-P13NWidget/UserGuide/**\n\n**Alias:** ["+
(d+"](https://phonetool.amazon.com/users/"+d+")\n**Comment:** "+b+"\n\n**Widget Group ID:** "+f.widgetGroupId+"\n**Strategy ID:** "+f.strategyId+"\n**CTI:** "+f.cti+"\n**Facets:** ")+(f.facets+"\n**Content Reftag:** "+f.reftag+"\n"+(""!==f.baseAsin?"**Page ASIN:** "+f.baseAsin+"\n":"")+"\n**SessionID:** ")+(f.sessionId+"\n**MarketplaceID:** "+f.marketplaceId+"\n**Device Type:** "+f.deviceType+"\n\n**List of ASINs:**\n\n")+g},J=function(a,c,b){var d=a.nextSibling;d&&d.classList.contains("report-problem-message")||
(d=document.createElement("h5"),d.classList.add("report-problem-message"),a.after(d));c?(d.classList.remove("a-color-error"),b.responseBody&&"object"===typeof b.responseBody?b.responseBody.response&&b.responseBody.response.id?d.innerHTML="Success, here's the <a href=\"https://t.corp.amazon.com/"+b.responseBody.response.id+'" target="_blank">SIM-T ticket</a> you created.':(u["default"].log("Fail to find the id of the SIM-T ticket created in the response body of response data.","ERROR"),d.innerText=
"Success, but we could not find the link to the SIM-T ticket."):(u["default"].log("The response body of response data is not an object.","ERROR"),d.innerText="Success, but we could not find the link to the SIM-T ticket.")):(d.classList.add("a-color-error"),d.innerText="string"===typeof b?b:"Oops! Something went wrong. Please try again.")},K=/(?=[ \-\/])|(?=[\u3105-\u312F])|(?=[\u31A0-\u31BA])|(?=[\u4E00-\u9FD5])|(?=[\u3400-\u4DB5])|(?=[\uF900-\uFAFF])|(?=[\u3040-\u309F])|(?=[\u30A0-\u30FF])|(?=[\u3190-\u319F])/,
L=/[^\/\-\[\]():\s]/,la=function(a){var c=z["default"].$("<div>")[0];c.classList.add("p13n-sc-offscreen-truncate");var b=parseInt(a.getAttribute("data-rows")||"2",10),d=function(){var e=a.innerHTML;a.innerHTML="&hellip;";var p=a.clientHeight;a.innerHTML=e;return p}();if(b){if(d){var f=function(e){c.innerHTML=e;return Math.round(c.clientHeight/d)<=b},g=function(e,p){e=e.split(p);var n=Math.floor(a.clientWidth/12),q=function(h){c.classList.add("p13n-sc-offscreen-truncate");c.style.overflow="hidden";
c.textContent=h;a.appendChild(c);h=a.clientWidth>=a.scrollWidth;a.removeChild(c);return h},k=function(h){var r=h.length-n;h.trim().length>n&&!q(h)&&Array.prototype.slice.call(h).map(function(l,w){return w>n&&w<=r&&L.test(l)?"&shy;"+l:l});return h};return e.map(function(h){return k(h)}).join("")};return{truncate:function(){var e=a.innerHTML.trim(),p=a.textContent||"";e=g(e,K);a.appendChild(c);if(f(e))a.removeChild(c),a.innerHTML=e;else{var n=e.split(K);for(var q=1,k=n.length,h,r,l=0;q!==k;)if(h=Math.floor((k+
q)/2),r=n.slice(0,h).join("")+"&hellip;",f(r)){if(1>=k-h){for(l=h;0<l&&!L.test(n[l-1]);)l--;break}q=h}else k=h;n=0===l?void 0:n.slice(0,l).join("")+"&hellip;";n?(a.innerHTML=n,a.setAttribute("title",p)):(u["default"].log("Unable to successfully truncate line "+e,"ERROR"),a.removeChild(c))}}}}u["default"].log("Truncation element does not have a line height or it is zero","ERROR")}else u["default"].log("Truncation element missing necessary line number data","ERROR")},ma=function(a){var c=Array.prototype.slice.call(a.getElementsByClassName("p13n-sc-truncate"));
a=a.getElementsByClassName("p13n-sc-truncate-fallback");(window.CSS&&CSS.supports&&CSS.supports("-webkit-line-clamp","1")?c:c.concat(Array.prototype.slice.call(a))).filter(function(b){return!!b.offsetParent}).map(function(b){var d=la(b);d&&(d.truncate(),b.classList.add("p13n-sc-truncated"),b.classList.remove("p13n-sc-truncate"),b.classList.remove("p13n-sc-truncate-fallback"),b.className=b.className.replace(/p13n-sc-line-clamp-\d/g,""))})},G=function(a){return 0===Math.floor(a/10)?"0"+a.toString():
a.toString()},na=function(a){var c=a.dayscountdowntoendtemplate,b=a.expiredstring,d=a.hourscountdowntoendtemplate,f=a.minutescountdowntoendtemplate;a=parseInt(a.endtime,10);var g=Date.now();if(g<=a){b=null;var e=a-g;g=Math.floor(e/864E5);var p=Math.floor(e/36E5);a=Math.floor(e/6E4%60);e=Math.floor(e/1E3%60);if(1<g&&c&&(b=c,null!==b))return c=b.replace("${daysCount}",g.toString());f&&(b=0===p?f:d);return null!==b?(c=b.replace("_hours_",G(p)),c=c.replace("_minutes_",G(a)),c=c.replace("_seconds_",G(e))):
""}return b},oa=function(a){if(null!==a&&a.dataset.endtime)var c=setInterval(function(){a.innerText===a.dataset.expiredstring&&clearInterval(c);var b=na({dayscountdowntoendtemplate:a.dataset.dayscountdowntoendtemplate||"",endtime:a.dataset.endtime||"",expiredstring:a.dataset.expiredstring||"",hourscountdowntoendtemplate:a.dataset.hourscountdowntoendtemplate||"",minutescountdowntoendtemplate:a.dataset.minutescountdowntoendtemplate||""});a.innerText=b},1E3)},pa={initCarousel:function(a){return m.__awaiter(void 0,
void 0,void 0,function(){var c,b,d;return m.__generator(this,function(f){c=(a||{}).afterPageLoaded;b=t["default"].cardRoot.classList.contains("p13n-sc-shoveler")?[t["default"].cardRoot]:Array.prototype.slice.call(t["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler"));d=C["default"].setup(["getCarouselItems"]);if(null===b||void 0===b||!b.length)return[2];b.forEach(function(g){return m.__awaiter(void 0,void 0,void 0,function(){var e,p,n,q,k;return m.__generator(this,function(h){switch(h.label){case 0:e=
function(){z["default"].loadDynamicImage("[data-name]='"+k+"' .p13n-sc-dynamic-image");ma(g);da(g);null===c||void 0===c?void 0:c(g)};e();if(g.classList.contains("p13n-carousel-initialized"))return[2];g.classList.add("p13n-carousel-initialized");p=aa["default"].getCarousel(P.unscope(g));n=Z["default"].getCarousel(g);q=g.dataset||{};k=p.getAttr("name");return[4,Promise.all([n.initialized,ha(g)])];case 1:return h.sent(),ea(),z["default"].on("a:carousel:"+k+":change:pageSize",e),z["default"].on("a:carousel:"+
k+":change:loading",e),z["default"].on("a:carousel:"+k+":change:animating",e),z["default"].on("a:carousel:"+k+":change:fetchedItems",e),n.attachRemoteOperation(function(r){var l=r.indexes;r=r.ids;return d.getCarouselItems(m.__assign(m.__assign({},q),{ids:r,indexes:l,offset:String(l[0]||0)}))}),[2]}})})});return[2]})})}},qa=function(){var a,c=Array.prototype.slice.call(t["default"].cardRoot.querySelectorAll('[class*="dealsCardDealTimer"]'));try{for(var b=m.__values(c),d=b.next();!d.done;d=b.next())oa(d.value)}catch(g){var f=
{error:g}}finally{try{d&&!d.done&&(a=b.return)&&a.call(b)}finally{if(f)throw f.error;}}},x=function(a,c){a&&(c?E["default"].show(a):E["default"].hide(a))},M=function(a,c){return(a=c.getElementsByClassName(a))&&1===a.length?a[0]:void 0},A=function(a){B.count(a,(B.count(a)||0)+1)},ra=function(){function a(c,b,d,f,g,e,p,n){var q=this;this.throttledScrollAction=z["default"].throttle(function(){return m.__awaiter(q,void 0,void 0,function(){return m.__generator(this,function(k){switch(k.label){case 0:return[4,
this.getNextBatchIfBottomInView()];case 1:return k.sent(),[2]}})})},200);this.containerDataset=this.getContainerDataset(c);this.bottomOfListElement=b;this.containerForInsertion=d;this.insertFetchedItems=f;this.errorFetchingItemsElement=e;this.fetchAsinsRemoteOperation=g;this.spinnerFetchingItemsElement=p;this.batchSize=n||8;this.processingStatus={batchFailureCount:0,currentIndex:Number(c.dataset.indexOffset)||0,individualBatchAttemptsCount:0,isAllContentLoaded:!1,isProcessing:!1}}a.prototype.getContainerDataset=
function(c){if(!c.dataset||!c.dataset.asinList)throw Error("Dataset not present or does not contain required data!");return{asinList:JSON.parse(c.dataset.asinList),linkParameters:c.dataset.linkParameters||"{}",reftag:c.dataset.reftag||"",strategyId:c.dataset.strategyId||"",widgetGroupId:c.dataset.widgetGroupId||""}};a.prototype.getNextItemBatch=function(c){var b=this;this.processingStatus.individualBatchAttemptsCount+=1;this.processingStatus.isProcessing=!0;var d=this.processingStatus.currentIndex;
if(d>=this.containerDataset.asinList.length)return this.processingStatus.isAllContentLoaded=!0,Promise.resolve(void 0);x(this.spinnerFetchingItemsElement,!0);d=this.containerDataset.asinList.slice(d,d+this.batchSize);var f=d.map(function(g,e){return e+b.processingStatus.currentIndex});return this.fetchAsinsRemoteOperation({ids:d,indexes:f,linkparameters:this.containerDataset.linkParameters,offset:f[0].toString(),reftagprefix:this.containerDataset.reftag}).then(function(g){x(b.spinnerFetchingItemsElement,
!1);b.insertFetchedItems(c,g);b.processingStatus.batchFailureCount=0;b.processingStatus.currentIndex+=b.batchSize;b.processingStatus.individualBatchAttemptsCount=0;b.processingStatus.isProcessing=!1}).catch(function(g){console.log("Error fetching items: "+g);if(2<=b.processingStatus.individualBatchAttemptsCount){b.processingStatus.batchFailureCount+=1;if(2<=b.processingStatus.batchFailureCount){b.processingStatus.isProcessing=!0;x(b.spinnerFetchingItemsElement,!1);x(b.errorFetchingItemsElement,!0);
return}b.processingStatus.currentIndex+=b.batchSize}void b.getNextItemBatch(c)})};a.prototype.getNextBatchIfBottomInView=function(){return m.__awaiter(this,void 0,void 0,function(){return m.__generator(this,function(c){switch(c.label){case 0:if(this.processingStatus.isProcessing)return[3,3];this.processingStatus.isProcessing=!0;return E["default"].onScreen(this.bottomOfListElement,500)&&!this.processingStatus.isAllContentLoaded&&2>this.processingStatus.batchFailureCount?[4,this.getNextItemBatch(this.containerForInsertion)]:
[3,2];case 1:return c.sent(),[3,3];case 2:this.processingStatus.isProcessing=!1,c.label=3;case 3:return[2]}})})};a.prototype.isInErrorState=function(){return 2<=this.processingStatus.batchFailureCount};a.prototype.resetLazyLoading=function(){this.processingStatus.batchFailureCount=0;x(this.errorFetchingItemsElement,!1)};return a}(),ua=function(a,c,b){void 0===c&&(c=function(){});void 0===b&&(b=function(){});return m.__awaiter(void 0,void 0,void 0,function(){return m.__generator(this,function(d){switch(d.label){case 0:return a.dataset.event?
[4,sa(a.dataset.event,a,c,b)]:[3,2];case 1:return d.sent(),[3,5];case 2:return a.dataset.url?[4,ta(a.dataset.url,c,b)]:[3,4];case 3:return d.sent(),[3,5];case 4:u["default"].log("Element is missing dataset.url or dataset.event attribute"),b(),d.label=5;case 5:return[2]}})})},sa=function(a,c,b,d){return m.__awaiter(void 0,void 0,void 0,function(){var f,g,e,p,n,q;return m.__generator(this,function(k){switch(k.label){case 0:f=function(h){return m.__awaiter(void 0,void 0,void 0,function(){var r,l;return m.__generator(this,
function(w){switch(w.label){case 0:return r=function(y){y?b():(u["default"].log("Failed to call PPDS custom API"),d())},l=function(y){u["default"].log("Caught error when calling PPDS custom API: "+y.stack);d()},[4,h().then(r).catch(l)];case 1:return w.sent(),[2]}})})};g=function(h){return m.__awaiter(void 0,void 0,void 0,function(){var r;return m.__generator(this,function(l){switch(l.label){case 0:if(!c.dataset.asin)return[3,2];r={asin:c.dataset.asin};return[4,f(h.bind(null,r))];case 1:return l.sent(),
[3,3];case 2:u["default"].log("Element was missing required data: asin"),d(),l.label=3;case 3:return[2]}})})};e=a;switch(e){case "NOT_INTERESTED":return[3,1];case "DELETE_NOT_INTERESTED":return[3,5]}return[3,7];case 1:if(!c.dataset.asin)return[3,3];p={asin:c.dataset.asin,strategyId:c.dataset.strategyId,widgetGroupId:c.dataset.widgetGroupId};n=C["default"].setup(["recordNotInterested"]);return[4,f(n.recordNotInterested.bind(null,p))];case 2:return k.sent(),[3,4];case 3:u["default"].log("Element was missing required data: asin"),
d(),k.label=4;case 4:return[3,8];case 5:return q=C["default"].setup(["deleteNotInterested"]),[4,g(q.deleteNotInterested)];case 6:return k.sent(),[3,8];case 7:return u["default"].log("Invalid PPDS event type: "+a),d(),[3,8];case 8:return[2]}})})},ta=function(a,c,b){return m.__awaiter(void 0,void 0,void 0,function(){return m.__generator(this,function(d){switch(d.label){case 0:return[4,I["default"].post(a,{accepts:"text/html,*/*",contentType:"application/x-www-form-urlencoded"}).then(function(){c()}).catch(function(f){u["default"].log("Failed to call AJAX endpoint "+
a+" with error: "+f.message,"ERROR");b()})];case 1:return d.sent(),[2]}})})},va=function(a,c,b,d,f,g,e,p){var n=a.getElementsByClassName(d)[0],q=a.getElementsByClassName(f)[0],k=p?a.getElementsByClassName(p)[0]:void 0,h=a.querySelector(g);if(!q||!n||!h)throw Error("One or more elements to record feedback are not present.");d=function(r,l){r&&(r.onclick=function(){return m.__awaiter(void 0,void 0,void 0,function(){var w;return m.__generator(this,function(y){switch(y.label){case 0:return[4,ua(r,function(){x(h,
!1);x(q,l);x(n,!l);k&&(k.style.opacity=l?"0.3":"1");e&&A(e.prefix+":record-feedback:success")},function(){console.log("Failed to record feedback on click");x(h,!0);e&&A(e.prefix+":record-feedback:failure")})];case 1:return y.sent(),e&&(w=l?e.primaryAction:e.secondaryAction,A(e.prefix+":record-feedback:"+w)),[2]}})})})};c=M(c,a);d(c,!0);a=M(b,a);d(a,!1)},xa={feedbackModalInit:function(){var a=this,c={prefix:"p13n-desktop-feedback-modal",primaryAction:"not-interested",secondaryAction:"remove-not-interested"},
b=t["default"].cardRoot.querySelector(".p13n-desktop-canaries-kebab-data");if(b){A(c.prefix+":kebab:render");b.onclick=function(){return A(c.prefix+":kebab:click")};t["default"].cardRoot.querySelector(".p13n-desktop-feedback-modal-link").onclick=function(){return A(c.prefix+":modal:open")};var d=t["default"].cardRoot.querySelector(".p13n-ni-iyr-redirect");d&&(d.onclick=function(){return A(c.prefix+":iyr:click")});d=t["default"].cardRoot.getElementsByClassName("p13n-canaries-desktop-feedback-modal")[0];
if(!d)throw Error("Dataset not present or does not contain required data!");var f=d.querySelector("#endOfList"),g=t["default"].cardRoot.getElementsByClassName("p13n-desktop-feedback-modal-faceouts-list")[0],e=d.querySelector("#p13n-desktop-feedback-modal-loading-items"),p=d.querySelector("#p13n-desktop-feedback-modal-error-loading-items"),n=new ra(b,f,g,function(q,k){var h;if(k.hasChildNodes()){k=Array.from(k.childNodes);try{for(var r=m.__values(k),l=r.next();!l.done;l=r.next()){var w=l.value;k=w;
var y=k.getElementsByClassName("p13n-individual-feedbackButton")[0];va(k,"p13n-individual-feedbackButton","p13n-feedback-undo-button","p13n-desktop-feedback-modal-initial-faceout","p13n-desktop-feedback-modal-undo-faceout","#p13n-record-feedback-error-message",c,"p13n-feedback-list-asin-image");q.appendChild(w);y.dataset.strategyId=b.dataset.strategyId;y.dataset.widgetGroupId=b.dataset.widgetGroupId}}catch(wa){var N={error:wa}}finally{try{l&&!l.done&&(h=r.return)&&h.call(r)}finally{if(N)throw N.error;
}}}},function(q){return C["default"].setup(["getCanariesFeedbackModalItems"]).getCanariesFeedbackModalItems(q)},p,e);t["default"].cardRoot.querySelector(".p13n-desktop-feedback-modal-link").addEventListener("click",function(){return m.__awaiter(a,void 0,void 0,function(){return m.__generator(this,function(q){switch(q.label){case 0:return""!==g.innerHTML||n.isInErrorState()?[3,2]:[4,n.getNextItemBatch(g)];case 1:return q.sent(),[3,4];case 2:if(!n.isInErrorState())return[3,4];n.resetLazyLoading();return[4,
n.getNextItemBatch(g)];case 3:q.sent(),q.label=4;case 4:return[2]}})})});d.addEventListener("wheel",n.throttledScrollAction)}}};H._operationNames=["getCarouselItems","getCanariesFeedbackModalItems","deleteNotInterested","recordNotInterested"];H.card=function(){return m.__awaiter(void 0,void 0,void 0,function(){var a,c;return m.__generator(this,function(b){switch(b.label){case 0:return a=pa.initCarousel({afterPageLoaded:qa}),c=xa.feedbackModalInit(),[4,a];case 1:return b.sent(),[4,c];case 2:return b.sent(),
[2]}})})}});
