/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_unit_12 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] res
  );
  
  
  
  wire [16-1:0] M_math_res;
  math_unit_15 math (
    .a(a),
    .b(b),
    .alufn(alufn),
    .res(M_math_res)
  );
  wire [16-1:0] M_boolean_res;
  boolean_unit_16 boolean (
    .a(a),
    .b(b),
    .alufn(alufn),
    .res(M_boolean_res)
  );
  wire [16-1:0] M_shift_res;
  shift_unit_17 shift (
    .a(a),
    .b(b),
    .alufn(alufn),
    .res(M_shift_res)
  );
  wire [16-1:0] M_compare_res;
  compare_unit_18 compare (
    .a(a),
    .b(b),
    .alufn(alufn),
    .res(M_compare_res)
  );
  
  always @* begin
    res = 1'h0;
    
    case (alufn[4+1-:2])
      2'h0: begin
        res = M_math_res;
      end
      2'h1: begin
        res = M_boolean_res;
      end
      2'h2: begin
        res = M_shift_res;
      end
      2'h3: begin
        res = M_compare_res;
      end
    endcase
  end
endmodule
