/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg outled,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_display_led;
  reg [8-1:0] M_display_player_position;
  reg [24-1:0] M_display_tower_positions;
  reg [64-1:0] M_display_enemy_positions;
  reg [16-1:0] M_display_enemy_dirs;
  reg [12-1:0] M_display_tower_disks;
  reg [4-1:0] M_display_active_disk;
  hanoi_display_1 display (
    .clk(clk),
    .rst(rst),
    .player_position(M_display_player_position),
    .tower_positions(M_display_tower_positions),
    .enemy_positions(M_display_enemy_positions),
    .enemy_dirs(M_display_enemy_dirs),
    .tower_disks(M_display_tower_disks),
    .active_disk(M_display_active_disk),
    .led(M_display_led)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  reg [7:0] tower1;
  reg [7:0] tower2;
  reg [7:0] tower3;
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    io_led = io_dip;
    io_seg = 8'hff;
    io_sel = 4'hf;
    tower1 = 9'h087;
    tower2 = 9'h0cf;
    tower3 = 9'h0b6;
    led = io_dip[0+0+7-:8];
    M_display_active_disk = io_dip[16+4+3-:4];
    M_display_player_position = io_dip[0+0+7-:8];
    M_display_tower_positions = {tower1, tower2, tower3};
    M_display_enemy_dirs = 16'hffff;
    M_display_enemy_positions = 64'h0122446890b1d2f4;
    M_display_tower_disks[0+3-:4] = io_dip[8+0+3-:4];
    M_display_tower_disks[4+3-:4] = io_dip[8+4+3-:4];
    M_display_tower_disks[8+3-:4] = io_dip[16+0+3-:4];
    outled = M_display_led;
  end
endmodule
