/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_unit_18 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] res
  );
  
  
  
  reg [2:0] compare_code;
  
  always @* begin
    res = 1'h0;
    compare_code = alufn[0+2-:3];
    
    case (compare_code)
      3'h3: begin
        res = a == b;
      end
      3'h5: begin
        res = a < b;
      end
      3'h7: begin
        res = a <= b;
      end
    endcase
  end
endmodule
