/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module enemy_move_left_unit_20 (
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] res
  );
  
  
  
  reg [15:0] enemy_pos;
  reg [15:0] move_amount;
  
  reg [15:0] new_position;
  
  always @* begin
    enemy_pos = a;
    move_amount = b;
    new_position = 1'h0;
    new_position[5+2-:3] = enemy_pos[5+2-:3];
    new_position[0+4-:5] = enemy_pos - move_amount;
    res = new_position;
  end
endmodule
