/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module solo_msb_unit_21 (
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] res
  );
  
  
  
  integer i;
  
  always @* begin
    res = 1'h0;
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      if (a[(i)*1+0-:1] == 1'h1) begin
        res = 1'h1 << i;
      end
    end
  end
endmodule
