/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [15:0] manual_input;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_btn_cond_out;
  reg [1-1:0] M_btn_cond_in;
  button_conditioner_2 btn_cond (
    .clk(clk),
    .in(M_btn_cond_in),
    .out(M_btn_cond_out)
  );
  wire [1-1:0] M_corrupt_button_out;
  button_conditioner_2 corrupt_button (
    .clk(clk),
    .in(io_button[1+0-:1]),
    .out(M_corrupt_button_out)
  );
  wire [1-1:0] M_manual_reset_button_out;
  button_conditioner_2 manual_reset_button (
    .clk(clk),
    .in(io_button[2+0-:1]),
    .out(M_manual_reset_button_out)
  );
  wire [1-1:0] M_manual_step_button_out;
  button_conditioner_2 manual_step_button (
    .clk(clk),
    .in(io_button[3+0-:1]),
    .out(M_manual_step_button_out)
  );
  wire [2-1:0] M_segment_counter_value;
  counter_3 segment_counter (
    .clk(clk),
    .rst(rst),
    .value(M_segment_counter_value)
  );
  wire [1-1:0] M_slowclock_value;
  counter_4 slowclock (
    .clk(clk),
    .rst(rst),
    .value(M_slowclock_value)
  );
  wire [1-1:0] M_medclock_value;
  counter_5 medclock (
    .clk(clk),
    .rst(rst),
    .value(M_medclock_value)
  );
  wire [1-1:0] M_blink_out;
  blinker_6 blink (
    .clk(clk),
    .rst(rst),
    .out(M_blink_out)
  );
  wire [2-1:0] M_malu_state_display;
  wire [16-1:0] M_malu_out;
  manual_alu_7 malu (
    .clk(clk),
    .rst(rst),
    .in(manual_input),
    .confirm(M_manual_step_button_out),
    .state_display(M_malu_state_display),
    .out(M_malu_out)
  );
  
  wire [8-1:0] M_test_out;
  wire [16-1:0] M_test_alu_display;
  tester_8 test (
    .clk(M_slowclock_value),
    .rst(rst),
    .corrupt(M_corrupt_button_out),
    .man_reset(M_manual_reset_button_out),
    .out(M_test_out),
    .alu_display(M_test_alu_display)
  );
  
  always @* begin
    M_btn_cond_in = io_button[4+0-:1];
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out | M_btn_cond_out;
    led = M_malu_state_display;
    manual_input[0+7-:8] = io_dip[0+7-:8];
    manual_input[8+7-:8] = io_dip[8+7-:8];
    io_led[0+7-:8] = M_malu_out[0+7-:8];
    io_led[8+7-:8] = M_malu_out[8+7-:8];
    io_led[16+7-:8] = M_test_out;
    io_seg = 1'h0;
    io_sel = 1'h0;
    usb_tx = usb_rx;
  end
endmodule
