/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_unit_14 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  reg [1:0] inputs;
  reg [3:0] func;
  
  integer i;
  
  always @* begin
    out = 1'h0;
    func = alufn[0+3-:4];
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      inputs[1+0-:1] = a[(i)*1+0-:1];
      inputs[0+0-:1] = b[(i)*1+0-:1];
      out[(i)*1+0-:1] = func[(inputs)*1+0-:1];
    end
  end
endmodule
