/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module dff_b16_5 (
    input clk,
    input rst,
    input [15:0] write_val,
    input write_enable,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] M_register_d, M_register_q = 1'h0;
  
  always @* begin
    M_register_d = M_register_q;
    
    out = M_register_q;
    
    case (write_enable)
      1'h1: begin
        M_register_d = write_val;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_register_q <= 1'h0;
    end else begin
      M_register_q <= M_register_d;
    end
  end
  
endmodule
