/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module full_adder_18 (
    input x,
    input y,
    input cin,
    output reg s,
    output reg cout
  );
  
  
  
  always @* begin
    s = x ^ y ^ cin;
    cout = x & y | cin & (x ^ y);
  end
endmodule
