/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module toggle_clock_8 (
    input clk,
    input rst,
    input pause,
    output reg value
  );
  
  
  
  wire [1-1:0] M_slowclock_value;
  counter_10 slowclock (
    .clk(clk),
    .rst(rst),
    .value(M_slowclock_value)
  );
  
  always @* begin
    if (~pause) begin
      value = M_slowclock_value;
    end else begin
      value = 1'h0;
    end
  end
endmodule
