/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_unit_16 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (alufn[1+1-:2])
      2'h1: begin
        out = z;
      end
      2'h2: begin
        out = n ^ v;
      end
      2'h3: begin
        out = z + (n ^ v);
      end
    endcase
  end
endmodule
