/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module reverse_17 (
    input [15:0] number,
    input [2:0] select,
    input reverse_all,
    output reg [15:0] out
  );
  
  
  
  integer i;
  integer j;
  
  always @* begin
    if (reverse_all) begin
      for (i = 1'h0; i < 5'h10; i = i + 1) begin
        j = 4'hf - i;
        out[(i)*1+0-:1] = number[(j)*1+0-:1];
      end
    end else begin
      out = number;
      for (i = 1'h0; i < 4'h8; i = i + 1) begin
        if (select == i) begin
          j = 4'hf - i;
          out[(j)*1+0-:1] = number[(i)*1+0-:1];
          out[(i)*1+0-:1] = number[(j)*1+0-:1];
        end
      end
    end
  end
endmodule
