/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module segment_decoder_9 (
    input clk,
    input rst,
    input [1:0] segment_no,
    input [3:0] segment_digit,
    input clear,
    input decimal,
    output reg [3:0] io_sel,
    output reg [7:0] io_out
  );
  
  
  
  always @* begin
    io_out = 8'h00;
    io_sel = 4'hf;
    
    case (segment_no)
      2'h0: begin
        io_sel = 4'he;
      end
      2'h1: begin
        io_sel = 4'hd;
      end
      2'h2: begin
        io_sel = 4'hb;
      end
      2'h3: begin
        io_sel = 4'h7;
      end
    endcase
    
    case (clear)
      1'h1: begin
        io_out = 7'h00;
      end
    endcase
    
    case (segment_digit)
      4'h0: begin
        io_out = 8'hc0;
      end
      4'h1: begin
        io_out = 8'hf9;
      end
      4'h2: begin
        io_out = 8'ha4;
      end
      4'h3: begin
        io_out = 8'hb0;
      end
      4'h4: begin
        io_out = 8'h99;
      end
      4'h5: begin
        io_out = 8'h92;
      end
      4'h6: begin
        io_out = 8'h82;
      end
      4'h7: begin
        io_out = 8'hf8;
      end
      4'h8: begin
        io_out = 8'h80;
      end
      4'h9: begin
        io_out = 8'h98;
      end
      4'ha: begin
        io_out = 8'h88;
      end
      4'hb: begin
        io_out = 8'h83;
      end
      4'hc: begin
        io_out = 8'hc6;
      end
      4'hd: begin
        io_out = 8'ha1;
      end
      4'he: begin
        io_out = 8'h86;
      end
      4'hf: begin
        io_out = 8'h8e;
      end
    endcase
    
    case (decimal)
      1'h1: begin
        io_out[7+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
