/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_15 (
    input [15:0] number,
    input [3:0] bits,
    input [2:0] shift_type,
    output reg [15:0] out
  );
  
  
  
  localparam LEFT_SHIFT = 3'h0;
  
  localparam RIGHT_SHIFT = 3'h1;
  
  localparam LEFT_ARITH_SHIFT = 3'h2;
  
  localparam RIGHT_ARITH_SHIFT = 3'h3;
  
  localparam LEFT_ROTATE = 3'h4;
  
  localparam RIGHT_ROTATE = 3'h5;
  
  always @* begin
    out = number;
    
    case (shift_type)
      3'h0: begin
        out = number << bits;
      end
      3'h1: begin
        out = number >> bits;
      end
      3'h2: begin
        out = $signed(number) <<< bits;
      end
      3'h3: begin
        out = $signed(number) >>> bits;
      end
      3'h4: begin
        out = (number << bits) | (number >> (5'h10 - bits));
      end
      3'h5: begin
        out = (number >> bits) | (number << (5'h10 - bits));
      end
    endcase
  end
endmodule
