/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_16 (
    input [15:0] number,
    input [3:0] bits,
    input [1:0] shift_type,
    output reg [15:0] out
  );
  
  
  
  localparam LEFT_SHIFT = 2'h0;
  
  localparam RIGHT_SHIFT = 2'h1;
  
  localparam LEFT_ARITH_SHIFT = 2'h2;
  
  localparam RIGHT_ARITH_SHIFT = 2'h3;
  
  localparam FILL_WITH_ONES = 16'hffff;
  
  always @* begin
    out = number;
    
    case (shift_type)
      2'h0: begin
        out = number << bits;
      end
      2'h1: begin
        out = number >> bits;
      end
      2'h2: begin
        out = number <<< bits;
      end
      2'h3: begin
        out = number >>> bits;
        if (number[15+0-:1]) begin
          
          case (bits)
            1'h1: begin
              out[14+1-:2] = 16'hffff;
            end
            2'h2: begin
              out[13+2-:3] = 16'hffff;
            end
            2'h3: begin
              out[12+3-:4] = 16'hffff;
            end
            3'h4: begin
              out[11+4-:5] = 16'hffff;
            end
            3'h5: begin
              out[10+5-:6] = 16'hffff;
            end
            3'h6: begin
              out[9+6-:7] = 16'hffff;
            end
            3'h7: begin
              out[8+7-:8] = 16'hffff;
            end
            4'h8: begin
              out[7+8-:9] = 16'hffff;
            end
            4'h9: begin
              out[6+9-:10] = 16'hffff;
            end
            4'ha: begin
              out[5+10-:11] = 16'hffff;
            end
            4'hb: begin
              out[4+11-:12] = 16'hffff;
            end
            4'hc: begin
              out[3+12-:13] = 16'hffff;
            end
            4'hd: begin
              out[2+13-:14] = 16'hffff;
            end
            4'he: begin
              out[1+14-:15] = 16'hffff;
            end
            4'hf: begin
              out = 16'hffff;
            end
          endcase
        end
      end
    endcase
  end
endmodule
