/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_15 (
    input [15:0] number,
    input [3:0] bits,
    input [1:0] shift_type,
    output reg [15:0] out
  );
  
  
  
  localparam LEFT_SHIFT = 2'h2;
  
  localparam RIGHT_SHIFT = 2'h1;
  
  localparam RIGHT_ARITH_SHIFT = 2'h3;
  
  always @* begin
    out = number;
    if (shift_type == 2'h2) begin
      out = number << bits;
    end else begin
      if (shift_type == 2'h1) begin
        out = number >> bits;
      end else begin
        if (shift_type == 2'h3) begin
          out = $signed(number) >>> bits;
        end
      end
    end
  end
endmodule
